const actionType = {
    CHANNELS: 'channel/CHANNELS',
    CHANNELS_FAILURE: 'channel/CHANNELS_FAILURE',
    CHANNELS_SUCCESS: 'channel/CHANNELS_SUCCESS',
    CHANNELS_RESET: 'channel/CHANNELS_RESET',
    CHANNELS_INSERTSUCCESS: 'channel/CHANNELS_INSERTSUCCESS',
    CHANNELS_INSERTSUCCESS_RESET: 'channel/CHANNELS_INSERTSUCCESS_RESET',

    INSERT_CHANNEL: 'channel/INSERT_CHANNEL',
    INSERT_CHANNEL_SUCCESS: 'channel/INSERT_CHANNEL_SUCCESS',
    INSERT_CHANNEL_FAILURE: 'channel/INSERT_CHANNEL_FAILURE',
    INSERT_CHANNEL_RESET: 'channel/INSERT_CHANNEL_RESET',

    EDIT_CHANNEL: 'channel/EDIT_CHANNEL',
    EDIT_CHANNEL_SUCCESS: 'channel/EDIT_CHANNEL_SUCCESS',
    EDIT_CHANNEL_FAILURE: 'channel/EDIT_CHANNEL_FAILURE',
    EDIT_CHANNEL_RESET: 'channel/EDIT_CHANNEL_RESET',

    CHECK_PAYMENTPLAN: 'channel/CHECK_PAYMENTPLAN',
    CHECK_PAYMENTPLAN_SUCCESS: 'channel/CHECK_PAYMENTPLAN_SUCCESS',
    CHECK_PAYMENTPLAN_FAILURE: 'channel/CHECK_PAYMENTPLAN_FAILURE',
    CHECK_PAYMENTPLAN_RESET: 'channel/CHECK_PAYMENTPLAN_RESET',

    ACTIVATECHANNEL: 'channel/ACTIVATECHANNEL',
    ACTIVATECHANNEL_SUCCESS: 'channel/ACTIVATECHANNEL_SUCCESS',
    ACTIVATECHANNEL_FAILURE: 'channel/ACTIVATECHANNEL_FAILURE',
    ACTIVATECHANNEL_RESET: 'channel/ACTIVATECHANNEL_RESET',
};

export default actionType;
