const actionType = {
    INIT_SDK: 'voximplant/INIT_SDK',
    MAKE_CALL: 'voximplant/MAKE_CALL',
    INIT_CALL: 'voximplant/INIT_CALL',
    MODIFY_CALL: 'voximplant/MODIFY_CALL',
    MANAGE_STATUS_CALL: 'voximplant/MANAGE_STATUS_CALL',
    MANAGE_STATUS_VOX: 'voximplant/MANAGE_STATUS_VOX',


    MANAGE_CONNECTION: 'voximplant/MANAGE_CONNECTION',
    ANSWER_CALL: 'voximplant/ANSWER_CALL',
    REJECT_CALL: 'voximplant/REJECT_CALL',
    HANGUP_CALL: 'voximplant/HANGUP_CALL',
    HOLD_CALL: 'voximplant/HOLD_CALL',
    MUTE_CALL: 'voximplant/MUTE_CALL',
    UNMUTE_CALL: 'voximplant/UNMUTE_CALL',

    SET_TRANSFER_ACTION: 'voximplant/SET_TRANSFER_ACTION',
    TRANSFER_CALL: 'voximplant/TRANSFER_CALL',
    INIT_TRANSFER_CALL: 'voximplant/INIT_TRANSFER_CALL',
    CONNECTED_TRANSFER_CALL: 'voximplant/CONNECTED_TRANSFER_CALL',
    COMPLETE_TRANSFER_CALL: 'voximplant/COMPLETE_TRANSFER_CALL',
    SET_TRANSFER_CALL: 'voximplant/SET_TRANSFER_CALL',
    HANGUP_TRANSFER_CALL: 'voximplant/HANGUP_TRANSFER_CALL',
    HOLD_TRANSFER_CALL: 'voximplant/HOLD_TRANSFER_CALL',
    MUTE_TRANSFER_CALL: 'voximplant/MUTE_TRANSFER_CALL',
    UNMUTE_TRANSFER_CALL: 'voximplant/UNMUTE_TRANSFER_CALL',
    RESET_TRANSFER_CALL: 'voximplant/RESET_TRANSFER_CALL',

    SET_MODAL_CALL: 'voximplant/SET_MODAL_CALL',
    SET_PHONE_NUMBER: 'voximplant/SET_PHONE_NUMBER',
    SET_HOLD: 'voximplant/SET_HOLD',
    SET_MUTE: 'voximplant/SET_MUTE',
    DISCONNECT: 'voximplant/DISCONNECT',
    RESET_CALL: 'voximplant/RESET_CALL',

    GET_CATEGORIES: 'voximplant/GET_CATEGORIES',
    GET_CATEGORIES_FAILURE: 'voximplant/GET_CATEGORIES_FAILURE',
    GET_CATEGORIES_SUCCESS: 'voximplant/GET_CATEGORIES_SUCCESS',
    GET_CATEGORIES_RESET: 'voximplant/GET_CATEGORIES_RESET',

    GET_COUNTRYSTATES: 'voximplant/GET_COUNTRYSTATES',
    GET_COUNTRYSTATES_FAILURE: 'voximplant/GET_COUNTRYSTATES_FAILURE',
    GET_COUNTRYSTATES_SUCCESS: 'voximplant/GET_COUNTRYSTATES_SUCCESS',
    GET_COUNTRYSTATES_RESET: 'voximplant/GET_COUNTRYSTATES_RESET',

    GET_REGIONS: 'voximplant/GET_REGIONS',
    GET_REGIONS_FAILURE: 'voximplant/GET_REGIONS_FAILURE',
    GET_REGIONS_SUCCESS: 'voximplant/GET_REGIONS_SUCCESS',
    GET_REGIONS_RESET: 'voximplant/GET_REGIONS_RESET',

    GET_HISTORY: 'voximplant/GET_HISTORY',
    GET_HISTORY_FAILURE: 'voximplant/GET_HISTORY_FAILURE',
    GET_HISTORY_SUCCESS: 'voximplant/GET_HISTORY_SUCCESS',
    GET_HISTORY_RESET: 'voximplant/GET_HISTORY_RESET',

    GET_ADVISORS: 'voximplant/GET_ADVISORS',
    GET_ADVISORS_FAILURE: 'voximplant/GET_ADVISORS_FAILURE',
    GET_ADVISORS_SUCCESS: 'voximplant/GET_ADVISORS_SUCCESS',
    GET_ADVISORS_RESET: 'voximplant/GET_ADVISORS_RESET',

    GET_MAXIMUMCONSUMPTION: 'voximplant/GET_MAXIMUMCONSUMPTION',
    GET_MAXIMUMCONSUMPTION_FAILURE: 'voximplant/GET_MAXIMUMCONSUMPTION_FAILURE',
    GET_MAXIMUMCONSUMPTION_SUCCESS: 'voximplant/GET_MAXIMUMCONSUMPTION_SUCCESS',
    GET_MAXIMUMCONSUMPTION_RESET: 'voximplant/GET_MAXIMUMCONSUMPTION_RESET',

    TRANSFER_ACCOUNTBALANCE: 'voximplant/TRANSFER_ACCOUNTBALANCE',
    TRANSFER_ACCOUNTBALANCE_FAILURE: 'voximplant/TRANSFER_ACCOUNTBALANCE_FAILURE',
    TRANSFER_ACCOUNTBALANCE_SUCCESS: 'voximplant/TRANSFER_ACCOUNTBALANCE_SUCCESS',
    TRANSFER_ACCOUNTBALANCE_RESET: 'voximplant/TRANSFER_ACCOUNTBALANCE_RESET',

    GET_ACCOUNTBALANCE: 'voximplant/GET_ACCOUNTBALANCE',
    GET_ACCOUNTBALANCE_FAILURE: 'voximplant/GET_ACCOUNTBALANCE_FAILURE',
    GET_ACCOUNTBALANCE_SUCCESS: 'voximplant/GET_ACCOUNTBALANCE_SUCCESS',
    GET_ACCOUNTBALANCE_RESET: 'voximplant/GET_ACCOUNTBALANCE_RESET',

    GET_CALLRECORD: 'voximplant/GET_CALLRECORD',
    GET_CALLRECORD_FAILURE: 'voximplant/GET_CALLRECORD_FAILURE',
    GET_CALLRECORD_SUCCESS: 'voximplant/GET_CALLRECORD_SUCCESS',
    GET_CALLRECORD_RESET: 'voximplant/GET_CALLRECORD_RESET',

    UPDATE_SCENARIO: 'voximplant/UPDATE_SCENARIO',
    UPDATE_SCENARIO_FAILURE: 'voximplant/UPDATE_SCENARIO_FAILURE',
    UPDATE_SCENARIO_SUCCESS: 'voximplant/UPDATE_SCENARIO_SUCCESS',
    UPDATE_SCENARIO_RESET: 'voximplant/UPDATE_SCENARIO_RESET',
};

export default actionType;