const actionType = {
    CATALOG_BUSINESSLIST: 'catalog/CATALOG_BUSINESSLIST',
    CATALOG_BUSINESSLIST_FAILURE: 'catalog/CATALOG_BUSINESSLIST_FAILURE',
    CATALOG_BUSINESSLIST_SUCCESS: 'catalog/CATALOG_BUSINESSLIST_SUCCESS',
    CATALOG_BUSINESSLIST_RESET: 'catalog/CATALOG_BUSINESSLIST_RESET',

    CATALOG_MANAGECATALOG: 'catalog/CATALOG_MANAGECATALOG',
    CATALOG_MANAGECATALOG_FAILURE: 'catalog/CATALOG_MANAGECATALOG_FAILURE',
    CATALOG_MANAGECATALOG_SUCCESS: 'catalog/CATALOG_MANAGECATALOG_SUCCESS',
    CATALOG_MANAGECATALOG_RESET: 'catalog/CATALOG_MANAGECATALOG_RESET',
};

export default actionType;