const actionType = {
    CATALOG_BUSINESSLIST: 'catalog/CATALOG_BUSINESSLIST',
    CATALOG_BUSINESSLIST_FAILURE: 'catalog/CATALOG_BUSINESSLIST_FAILURE',
    CATALOG_BUSINESSLIST_SUCCESS: 'catalog/CATALOG_BUSINESSLIST_SUCCESS',
    CATALOG_BUSINESSLIST_RESET: 'catalog/CATALOG_BUSINESSLIST_RESET',

    CATALOG_MANAGECATALOG: 'catalog/CATALOG_MANAGECATALOG',
    CATALOG_MANAGECATALOG_FAILURE: 'catalog/CATALOG_MANAGECATALOG_FAILURE',
    CATALOG_MANAGECATALOG_SUCCESS: 'catalog/CATALOG_MANAGECATALOG_SUCCESS',
    CATALOG_MANAGECATALOG_RESET: 'catalog/CATALOG_MANAGECATALOG_RESET',

    CATALOG_SYNCHROCATALOG: 'catalog/CATALOG_SYNCHROCATALOG',
    CATALOG_SYNCHROCATALOG_FAILURE: 'catalog/CATALOG_SYNCHROCATALOG_FAILURE',
    CATALOG_SYNCHROCATALOG_SUCCESS: 'catalog/CATALOG_SYNCHROCATALOG_SUCCESS',
    CATALOG_SYNCHROCATALOG_RESET: 'catalog/CATALOG_SYNCHROCATALOG_RESET',

    CATALOG_SYNCHROPRODUCT: 'catalog/CATALOG_SYNCHROPRODUCT',
    CATALOG_SYNCHROPRODUCT_FAILURE: 'catalog/CATALOG_SYNCHROPRODUCT_FAILURE',
    CATALOG_SYNCHROPRODUCT_SUCCESS: 'catalog/CATALOG_SYNCHROPRODUCT_SUCCESS',
    CATALOG_SYNCHROPRODUCT_RESET: 'catalog/CATALOG_SYNCHROPRODUCT_RESET',

    CATALOG_IMPORTPRODUCT: 'catalog/CATALOG_IMPORTPRODUCT',
    CATALOG_IMPORTPRODUCT_FAILURE: 'catalog/CATALOG_IMPORTPRODUCT_FAILURE',
    CATALOG_IMPORTPRODUCT_SUCCESS: 'catalog/CATALOG_IMPORTPRODUCT_SUCCESS',
    CATALOG_IMPORTPRODUCT_RESET: 'catalog/CATALOG_IMPORTPRODUCT_RESET',

    CATALOG_MANAGEPRODUCT: 'catalog/CATALOG_MANAGEPRODUCT',
    CATALOG_MANAGEPRODUCT_FAILURE: 'catalog/CATALOG_MANAGEPRODUCT_FAILURE',
    CATALOG_MANAGEPRODUCT_SUCCESS: 'catalog/CATALOG_MANAGEPRODUCT_SUCCESS',
    CATALOG_MANAGEPRODUCT_RESET: 'catalog/CATALOG_MANAGEPRODUCT_RESET',

    CATALOG_DELETEPRODUCT: 'catalog/CATALOG_DELETEPRODUCT',
    CATALOG_DELETEPRODUCT_FAILURE: 'catalog/CATALOG_DELETEPRODUCT_FAILURE',
    CATALOG_DELETEPRODUCT_SUCCESS: 'catalog/CATALOG_DELETEPRODUCT_SUCCESS',
    CATALOG_DELETEPRODUCT_RESET: 'catalog/CATALOG_DELETEPRODUCT_RESET',
};

export default actionType;