const actionType = {
    EXECUTECORP_MAIN: 'main/EXECUTECORP_MAIN',
    EXECUTECORP_MAIN_FAILURE: 'main/EXECUTECORP_MAIN_FAILURE',
    EXECUTECORP_MAIN_SUCCESS: 'main/EXECUTECORP_MAIN_SUCCESS',
    EXECUTECORP_MAIN_RESET: 'main/EXECUTECORP_MAIN_RESET',

    CORP_MAIN: 'CORP_MAIN',
    CORP_MAIN_SUCCESS: 'CORP_MAIN_SUCCESS',
    CORP_MAIN_FAILURE: 'CORP_MAIN_FAILURE',
    CORP_MAIN_RESET: 'CORP_MAIN_RESET',
};

export default actionType;