const actionType = {
    MAIN: 'main/MAIN',
    MAIN_FAILURE: 'main/MAIN_FAILURE',
    MAIN_SUCCESS: 'main/MAIN_SUCCESS',
    MAIN_RESET: 'main/MAIN_RESET',
    
    MULTI_MAIN: 'main/MULTI_MAIN',
    MULTI_MAIN_FAILURE: 'main/MULTI_MAIN_FAILURE',
    MULTI_MAIN_SUCCESS: 'main/MULTI_MAIN_SUCCESS',
    MULTI_MAIN_RESET: 'main/MULTI_MAIN_RESET',

    EXECUTE_MAIN: 'main/EXECUTE_MAIN',
    EXECUTE_MAIN_FAILURE: 'main/EXECUTE_MAIN_FAILURE',
    EXECUTE_MAIN_SUCCESS: 'main/EXECUTE_MAIN_SUCCESS',
    EXECUTE_MAIN_RESET: 'main/EXECUTE_MAIN_RESET',

    AUX_MAIN: 'main/AUX_MAIN',
    AUX_MAIN_FAILURE: 'main/AUX_MAIN_FAILURE',
    AUX_MAIN_SUCCESS: 'main/AUX_MAIN_SUCCESS',
    AUX_MAIN_RESET: 'main/AUX_MAIN_RESET',
    
    AUX2_MAIN: 'main/AUX2_MAIN',
    AUX2_MAIN_FAILURE: 'main/AUX2_MAIN_FAILURE',
    AUX2_MAIN_SUCCESS: 'main/AUX2_MAIN_SUCCESS',
    AUX2_MAIN_RESET: 'main/AUX_MAIN_RESET',

    AUX_MULTI_MAIN: 'main/AUX_MULTI_MAIN',
    AUX_MULTI_MAIN_FAILURE: 'main/AUX_MULTI_MAIN_FAILURE',
    AUX_MULTI_MAIN_SUCCESS: 'main/AUX_MULTI_MAIN_SUCCESS',
    AUX_MULTI_MAIN_RESET: 'main/AUX_MULTI_MAIN_RESET',

    PAGINATED_MAIN: 'main/PAGINATED_MAIN',
    PAGINATED_MAIN_FAILURE: 'main/PAGINATED_MAIN_FAILURE',
    PAGINATED_MAIN_SUCCESS: 'main/PAGINATED_MAIN_SUCCESS',
    PAGINATED_MAIN_RESET: 'main/PAGINATED_MAIN_RESET',

    UPLOAD_FILE: 'main/UPLOAD_FILE',
    UPLOAD_FILE_FAILURE: 'main/UPLOAD_FILE_FAILURE',
    UPLOAD_FILE_SUCCESS: 'main/UPLOAD_FILE_SUCCESS',
    UPLOAD_FILE_RESET: 'main/UPLOAD_FILE_RESET',
};

export default actionType;