const actionType = {
    MAIN: 'main/MAIN',
    MAIN_FAILURE: 'main/MAIN_FAILURE',
    MAIN_SUCCESS: 'main/MAIN_SUCCESS',
    MAIN_RESET: 'main/MAIN_RESET',
    
    MULTI_MAIN: 'main/MULTI_MAIN',
    MULTI_MAIN_FAILURE: 'main/MULTI_MAIN_FAILURE',
    MULTI_MAIN_SUCCESS: 'main/MULTI_MAIN_SUCCESS',
    MULTI_MAIN_RESET: 'main/MULTI_MAIN_RESET',

    EXECUTE_MAIN: 'main/EXECUTE_MAIN',
    EXECUTE_MAIN_FAILURE: 'main/EXECUTE_MAIN_FAILURE',
    EXECUTE_MAIN_SUCCESS: 'main/EXECUTE_MAIN_SUCCESS',
    EXECUTE_MAIN_RESET: 'main/EXECUTE_MAIN_RESET',
    
    TEST_REQUEST: 'main/TEST_REQUEST',
    TEST_REQUEST_FAILURE: 'main/TEST_REQUEST_FAILURE',
    TEST_REQUEST_SUCCESS: 'main/TEST_REQUEST_SUCCESS',
    TEST_REQUEST_RESET: 'main/TEST_REQUEST_RESET',

    AUX_MAIN: 'main/AUX_MAIN',
    AUX_MAIN_FAILURE: 'main/AUX_MAIN_FAILURE',
    AUX_MAIN_SUCCESS: 'main/AUX_MAIN_SUCCESS',
    AUX_MAIN_RESET: 'main/AUX_MAIN_RESET',
    
    AUX2_MAIN: 'main/AUX2_MAIN',
    AUX2_MAIN_FAILURE: 'main/AUX2_MAIN_FAILURE',
    AUX2_MAIN_SUCCESS: 'main/AUX2_MAIN_SUCCESS',
    AUX2_MAIN_RESET: 'main/AUX2_MAIN_RESET',

    AUX_MULTI_MAIN: 'main/AUX_MULTI_MAIN',
    AUX_MULTI_MAIN_FAILURE: 'main/AUX_MULTI_MAIN_FAILURE',
    AUX_MULTI_MAIN_SUCCESS: 'main/AUX_MULTI_MAIN_SUCCESS',
    AUX_MULTI_MAIN_RESET: 'main/AUX_MULTI_MAIN_RESET',

    AUX2_MULTI_MAIN: 'main/AUX2_MULTI_MAIN',
    AUX2_MULTI_MAIN_FAILURE: 'main/AUX2_MULTI_MAIN_FAILURE',
    AUX2_MULTI_MAIN_SUCCESS: 'main/AUX2_MULTI_MAIN_SUCCESS',
    AUX2_MULTI_MAIN_RESET: 'main/AUX2_MULTI_MAIN_RESET',

    PAGINATED_MAIN: 'main/PAGINATED_MAIN',
    PAGINATED_MAIN_FAILURE: 'main/PAGINATED_MAIN_FAILURE',
    PAGINATED_MAIN_SUCCESS: 'main/PAGINATED_MAIN_SUCCESS',
    PAGINATED_MAIN_RESET: 'main/PAGINATED_MAIN_RESET',

    AUX_PAGINATED_MAIN: 'main/AUX_PAGINATED_MAIN',
    AUX_PAGINATED_MAIN_FAILURE: 'main/AUX_PAGINATED_MAIN_FAILURE',
    AUX_PAGINATED_MAIN_SUCCESS: 'main/AUX_PAGINATED_MAIN_SUCCESS',
    AUX_PAGINATED_MAIN_RESET: 'main/AUX_PAGINATED_MAIN_RESET',

    GRAPHIC_MAIN: 'main/GRAPHIC_MAIN',
    GRAPHIC_MAIN_FAILURE: 'main/GRAPHIC_MAIN_FAILURE',
    GRAPHIC_MAIN_SUCCESS: 'main/GRAPHIC_MAIN_SUCCESS',
    GRAPHIC_MAIN_RESET: 'main/GRAPHIC_MAIN_RESET',

    UPLOAD_FILE: 'main/UPLOAD_FILE',
    UPLOAD_FILE_FAILURE: 'main/UPLOAD_FILE_FAILURE',
    UPLOAD_FILE_SUCCESS: 'main/UPLOAD_FILE_SUCCESS',
    UPLOAD_FILE_RESET: 'main/UPLOAD_FILE_RESET',

    EXPORT_DATA: 'main/EXPORT_DATA',
    EXPORT_DATA_FAILURE: 'main/EXPORT_DATA_FAILURE',
    EXPORT_DATA_SUCCESS: 'main/EXPORT_DATA_SUCCESS',
    EXPORT_DATA_RESET: 'main/EXPORT_DATA_RESET',

    DATA_DYNAMIC: 'main/DATA_DYNAMIC',
    DATA_DYNAMIC_FAILURE: 'main/DATA_DYNAMIC_FAILURE',
    DATA_DYNAMIC_SUCCESS: 'main/DATA_DYNAMIC_SUCCESS',
    DATA_DYNAMIC_RESET: 'main/DATA_DYNAMIC_RESET',

    MAIN_EVENT_BOOKING: 'main/MAIN_EVENT_BOOKING',
    MAIN_EVENT_BOOKING_FAILURE: 'main/MAIN_EVENT_BOOKING_FAILURE',
    MAIN_EVENT_BOOKING_SUCCESS: 'main/MAIN_EVENT_BOOKING_SUCCESS',
    MAIN_EVENT_BOOKING_RESET: 'main/MAIN_EVENT_BOOKING_RESET',

    DATA_EXPORT_DYNAMIC: 'main/DATA_EXPORT_DYNAMIC',
    DATA_EXPORT_DYNAMIC_FAILURE: 'main/DATA_EXPORT_DYNAMIC_FAILURE',
    DATA_EXPORT_DYNAMIC_SUCCESS: 'main/DATA_EXPORT_DYNAMIC_SUCCESS',
    DATA_EXPORT_DYNAMIC_RESET: 'main/DATA_EXPORT_DYNAMIC_RESET',
    
    RESET_ALL: 'main/RESET_ALL',
    
    VIEWCHANGE: 'main/VIEWCHANGE',
    CLEAN_VIEWCHANGE: 'main/CLEAN_VIEWCHANGE',
    SET_MEMORY_TABLE: 'main/SET_MEMORY_TABLE',
    CLEAN_MEMORY_TABLE: 'main/CLEAN_MEMORY_TABLE',
};

export default actionType;