const actionType = {
    ACTIVATIONUSER_SEND: 'activationuser/REQUEST_SEND',
    ACTIVATIONUSER_FAILURE: 'activationuser/REQUEST_FAILURE',
    ACTIVATIONUSER_SUCCESS: 'activationuser/REQUEST_SUCCESS',
    ACTIVATIONUSER_RESET: 'activationuser/REQUEST_RESET',

    EXECUTE_MAIN: 'user/EXECUTE_MAIN',
    EXECUTE_MAIN_FAILURE: 'user/EXECUTE_MAIN_FAILURE',
    EXECUTE_MAIN_SUCCESS: 'user/EXECUTE_MAIN_SUCCESS',
    EXECUTE_MAIN_RESET: 'user/EXECUTE_MAIN_RESET',

    DELUSER_SEND: 'deluser/REQUEST_SEND',
    DELUSER_FAILURE: 'deluser/REQUEST_FAILURE',
    DELUSER_SUCCESS: 'deluser/REQUEST_SUCCESS',
    DELUSER_RESET: 'deluser/REQUEST_RESET',
};

export default actionType;