const actionType = {
    POSTHISTORY_SCHEDULE: 'posthistory/POSTHISTORY_SCHEDULE',
    POSTHISTORY_SCHEDULE_FAILURE: 'posthistory/POSTHISTORY_SCHEDULE_FAILURE',
    POSTHISTORY_SCHEDULE_SUCCESS: 'posthistory/POSTHISTORY_SCHEDULE_SUCCESS',
    POSTHISTORY_SCHEDULE_RESET: 'posthistory/POSTHISTORY_SCHEDULE_RESET',
};

export default actionType;