const actionType = {
    CONVERSATIONDATA: 'inbox/CONVERSATIONDATA',
    CONVERSATIONDATA_SUCCESS: 'inbox/CONVERSATIONDATA_SUCCESS',
    CONVERSATIONDATA_FAILURE: 'inbox/CONVERSATIONDATA_FAILURE',
    CONVERSATIONDATA_RESET: 'inbox/CONVERSATIONDATA_RESET',

};

export default actionType;