const actionType = {
    CONVERSATIONDATA: 'inbox/CONVERSATIONDATA',
    CONVERSATIONDATA_SUCCESS: 'inbox/CONVERSATIONDATA_SUCCESS',
    CONVERSATIONDATA_FAILURE: 'inbox/CONVERSATIONDATA_FAILURE',
    CONVERSATIONDATA_RESET: 'inbox/CONVERSATIONDATA_RESET',

    INTERACTIONDATA: 'inbox/INTERACTIONDATA',
    INTERACTIONDATA_SUCCESS: 'inbox/INTERACTIONDATA_SUCCESS',
    INTERACTIONDATA_FAILURE: 'inbox/INTERACTIONDATA_FAILURE',
    INTERACTIONDATA_RESET: 'inbox/INTERACTIONDATA_RESET',
};

export default actionType;