const actionType = {
    GETLOCATION: 'GETLOCATION_MAIN',
    GETLOCATION_FAILURE: 'GETLOCATION_FAILURE',
    GETLOCATION_SUCCESS: 'GETLOCATION_SUCCESS',
    GETLOCATION_RESET: 'GETLOCATION_RESET',
};

export default actionType;