const actionTypes = {
    TRAINMODEL_SEND: 'rasaia/TRAINMODEL_SEND',
    TRAINMODEL_FAILURE: 'rasaia/TRAINMODEL_FAILURE',
    TRAINMODEL_SUCCESS: 'rasaia/TRAINMODEL_SUCCESS',
    TRAINMODEL_RESET: 'rasaia/TRAINMODEL_RESET',

    DOWNLOADMODEL_SEND: 'rasaia/DOWNLOADMODEL_SEND',
    DOWNLOADMODEL_FAILURE: 'rasaia/DOWNLOADMODEL_FAILURE',
    DOWNLOADMODEL_SUCCESS: 'rasaia/DOWNLOADMODEL_SUCCESS',
    DOWNLOADMODEL_RESET: 'rasaia/DOWNLOADMODEL_RESET',

    UPLOADMODEL_SEND: 'rasaia/UPLOADMODEL_SEND',
    UPLOADMODEL_FAILURE: 'rasaia/UPLOADMODEL_FAILURE',
    UPLOADMODEL_SUCCESS: 'rasaia/UPLOADMODEL_SUCCESS',
    UPLOADMODEL_RESET: 'rasaia/UPLOADMODEL_RESET',

    MODELLIST_SEND: 'rasaia/MODELLIST_SEND',
    MODELLIST_FAILURE: 'rasaia/MODELLIST_FAILURE',
    MODELLIST_SUCCESS: 'rasaia/MODELLIST_SUCCESS',
    MODELLIST_RESET: 'rasaia/MODELLIST_RESET',

    MODELDOWNLOAD_SEND: 'rasaia/MODELDOWNLOAD_SEND',
    MODELDOWNLOAD_FAILURE: 'rasaia/MODELDOWNLOAD_FAILURE',
    MODELDOWNLOAD_SUCCESS: 'rasaia/MODELDOWNLOAD_SUCCESS',
    MODELDOWNLOAD_RESET: 'rasaia/MODELDOWNLOAD_RESET',
};

export default actionTypes;