const actionType = {
    GETVERSION: 'GETVERSION_MAIN',
    GETVERSION_FAILURE: 'GETVERSION_FAILURE',
    GETVERSION_SUCCESS: 'GETVERSION_SUCCESS',
    GETVERSION_RESET: 'GETVERSION_RESET',
};

export default actionType;