export const columnsHideGraphic = {
    interaction: {
        interactiondatehour: true,
        channel: true,  
        agent: true,
        ticketgroup: true,
        person: true,
        originalname: true,
        clientnumber: true,
        email: true,
        personcommunicationchannel: true,
    }
}
export const columnsHideShow = {
    productivity: {
        email: true,
        starttime: true,
        endtime: true,
        derivationdate: true,
        derivationtime: true, 
        firstinteractiondateagent: true,
        firstinteractiontime: true,
        tmo: true, 
        tmoagent: true,
        tmeagent: true,
        holdingholdtime: true,
        suspensiontime: true, 
        avgagentresponse: true,
        swingingtimes: true,
        tags: true,  
    },
    campaignreport: {
        executiontype: true,
        executionuser: true,
        executionuserprofile: true,
        total: true,
        success: true, 
        successp: true,
        fail: true,
        failp: true, 
        attended: true,
        locked: true,
        blacklisted: true,      
    },
    tipification: {       
        enddate: true,
        endtime: true,
        firstinteractiondate: true,
        firstinteractiontime: true, 
        person: true,
        phone: true,
        closedby: true, 
        agent: true,
        closetype: true,
        channel: true,  
    },
    interaction: {
        interactiondatehour: true,
        channel: true,  
        agent: true,
        ticketgroup: true,
        person: true,
        originalname: true,
        clientnumber: true,
        email: true,
        personcommunicationchannel: true,
    }
}