export const columnsHideGraphic = {
    interaction: {
        interactiondatehour: true,
        channel: true,  
        agent: true,
        ticketgroup: true,
        person: true,
        originalname: true,
        clientnumber: true,
        email: true,
        personcommunicationchannel: true,
    },
    userproductivityhours: {
        busytimewithinwork: true,
        freetimewithinwork: true,  
        busytimeoutsidework: true,
        availabletime: true,
        idletime: true,
        idletimewithoutattention: true,
        qtydisconnection: true,   
    },   
    reportvoicecall: {
        ticketnum: true,
        tickettime: true,  
        finishtime: true,
        handoffdate: true,
        phone: true,
        totalduration: true,
        agentduration: true,  
        customerwaitingduration: true,
        holdingtime: true,  
        transferduration: true,
    },
    loginhistory: {
        datehour: true,
        motivedescription: true,         
    },
};

export interface ColumnsInterface {
    [key: string]: {
        [key: string]: boolean;
    };
}

export const columnsHideShow: ColumnsInterface = {
    productivity: {
        email: true,
        starttime: true,
        endtime: true,
        derivationdate: true,
        derivationtime: true, 
        firstinteractiondateagent: true,
        firstinteractiontime: true,
        tmo: true, 
        tmoagent: true,
        tmeagent: true,
        holdingholdtime: true,
        suspensiontime: true, 
        avgagentresponse: true,
        swingingtimes: true,
        tags: true,  
    },
    campaignreport: {
        executiontype: true,
        executionuser: true,
        executionuserprofile: true,
        total: true,
        success: true, 
        successp: true,
        fail: true,
        failp: true, 
        attended: true,
        locked: true,
        blacklisted: true,      
    },
    tipification: {       
        enddate: true,
        endtime: true,
        firstinteractiondate: true,
        firstinteractiontime: true, 
        person: true,
        phone: true,
        closedby: true, 
        agent: true,
        closetype: true,
        channel: true,  
    },
    interaction: {
        interactiondatehour: true,
        channel: true,  
        agent: true,
        ticketgroup: true,
        person: true,
        originalname: true,
        clientnumber: true,
        email: true,
        personcommunicationchannel: true,
    },
    userproductivityhours: {
        busytimewithinwork: true,
        freetimewithinwork: true,  
        busytimeoutsidework: true,
        availabletime: true,
        idletime: true,
        qtyconnection: true,
        qtydisconnection: true,   
    },
    reportrequestsd: {
        channel: true,
        resolution: true,  
        reportdate: true,
        dateofresolution: true,       
    },
    loginhistory: {
        username: true,
        type: true,  
        motivedescription: true,
    },     
}


export const columnGroupedBy: ColumnsInterface = {
    productivity: {
        ticket: true,
        ticketyear: true,  
        ticketmonth: true,
        ticketweek: true,
        ticketday: true,
        tickethour: true,  
        channel: true,
        origin: true,
        person: true,
        phone: true,  
        closedby: true,
        agent: true,
        ticketgroup: true,
        startdate: true,  
        enddate: true,      
    },
    loginhistory: { //actualmente visible //chequear funcionalidad, no funciona en nusuario, usuario, estado, tipo
        user: true,
        username: true,
        status: true,  
        type: true,
    }, 
    inputretry: { 
        person: true,      
    }, 
    interaction: {
        ticketnum: true,
        ticketyear: true,  
        ticketmonth: true,
        channel: true,
        agent: true,
        intent: true,  
        interactiontype: true,
        ticketgroup: true,
        person: true,
        personcommunicationchannel: true,          
    },
    campaignreport: {
        title: true,
        description: true,
        templatetype: true,
        templatename: true,
        channel: true,
        executiontype: true,
        executionuser: true,
        executionuserprofile: true,       
    },
    productividadasesores: {        
        fullname: true,
        totaltickets: true,
        closedtickets: true,
        asignedtickets: true,
        suspendedtickets: true,
        cardavgmaxtmo: true,
        cardmaxmaxtmouser: true,
        cardavgmintmo: true,
        cardminmintmouser: true,
        conectadotime: true,
        userstatus: true,        
    },
    tipification: {      
        ticket: true,
        enddate: true,
        firstinteractiondate: true,
        person: true,
        closedby: true,
        agent: true,
        closetype: true,     
        channel: true,
        classificationlevel1: true,
        classificationlevel2: true,
        classificationlevel3: true,        
    },
    userproductivityhours: {
        datehour: true,
        agent: true,
        hoursrange: true,
        worktime: true,
        onlinetime: true,
        qtytickets: true,
    },
    reportrequestsd: {
        sd_request: true,
        type: true,
        channel: true,
        display_name: true,
        company: true,
        description: true,
        priority: true,  
        phase: true,
        resolution: true,
        report_date: true,
        resolution_date: true,     
    },   
    ticketvsadviser: {
        fechainicio: true,
        asesor: true,
        canal: true,
        tipocierre: true,
        fechacierre: true,       
    },
    reportvoicecall: {
        channel: true,
        ticketdate: true,
        agent: true,
        name: true,
        origin: true,
        closetype: true,
        classification: true,      
    }
  };

