const actionType = {
    LOGIN: 'login/LOGIN',
    LOGIN_FAILURE: 'login/LOGIN_FAILURE',
    LOGIN_SUCCESS: 'login/LOGIN_SUCCESS',
    LOGIN_RESET: 'login/LOGIN_RESET',
    VALIDATE_TOKEN: 'login/VALIDATE_TOKEN',
    VALIDATE_TOKEN_FAILURE: 'login/VALIDATE_TOKEN_FAILURE',
    VALIDATE_TOKEN_SUCCESS: 'login/VALIDATE_TOKEN_SUCCESS',
    VALIDATE_TOKEN_RESET: 'login/VALIDATE_TOKEN_RESET',
    CHANGE_ORGANIZATION: 'login/CHANGE_ORGANIZATION',
    CHANGE_ORGANIZATION_FAILURE: 'login/CHANGE_ORGANIZATION_FAILURE',
    CHANGE_ORGANIZATION_SUCCESS: 'login/CHANGE_ORGANIZATION_SUCCESS',
    CHANGE_ORGANIZATION_RESET: 'login/CHANGE_ORGANIZATION_RESET',
    CHANGE_DATA_USER: 'login/CHANGE_DATA_USER',
    CHANGE_UICONFIG_USER: 'login/CHANGE_UICONFIG_USER',

    LOGOUT: 'login/LOGOUT',
    LOGOUT_FAILURE: 'login/LOGOUT_FAILURE',
    LOGOUT_SUCCESS: 'login/LOGOUT_SUCCESS',
    LOGOUT_RESET: 'login/LOGOUT_RESET',
    
    INVOKE_INCREMENTAL: 'login/INVOKE_INCREMENTAL',
    INVOKE_INCREMENTAL_FAILURE: 'login/INVOKE_INCREMENTAL_FAILURE',
    INVOKE_INCREMENTAL_SUCCESS: 'login/INVOKE_INCREMENTAL_SUCCESS',
    INVOKE_INCREMENTAL_RESET: 'login/INVOKE_INCREMENTAL_RESET',

    CHANGE_PWD_FIRST_LOGIN: 'login/CHANGE_PWD_FIRST_LOGIN',
    NEW_NOTIFICATION: 'login/NEW_NOTIFICATION',
    UPDATE_CONNECTION: 'login/UPDATE_CONNECTION',
    CLEAN_VALIDATETOKEN: 'login/CLEAN_VALIDATETOKEN',
    NEW_UPDATE_ORG: 'login/NEW_UPDATE_ORG',

    UPDATE_LANGUAGE: 'login/UPDATE_LANGUAGE'
};

export default actionType;