const actionType = {
    LOGIN: 'login/LOGIN',
    LOGIN_FAILURE: 'login/LOGIN_FAILURE',
    LOGIN_SUCCESS: 'login/LOGIN_SUCCESS',
    LOGIN_RESET: 'login/LOGIN_RESET',

    VALIDATE_TOKEN: 'login/VALIDATE_TOKEN',
    VALIDATE_TOKEN_FAILURE: 'login/VALIDATE_TOKEN_FAILURE',
    VALIDATE_TOKEN_SUCCESS: 'login/VALIDATE_TOKEN_SUCCESS',
    VALIDATE_TOKEN_RESET: 'login/VALIDATE_TOKEN_RESET',

    LOGOUT: 'login/LOGOUT',
    LOGOUT_FAILURE: 'login/LOGOUT_FAILURE',
    LOGOUT_SUCCESS: 'login/LOGOUT_SUCCESS',
    LOGOUT_RESET: 'login/LOGOUT_RESET',
};

export default actionType;