const actionType = {
    CAMPAIGN_START: 'campaign/CAMPAIGN_START',
    CAMPAIGN_START_FAILURE: 'campaign/CAMPAIGN_START_FAILURE',
    CAMPAIGN_START_SUCCESS: 'campaign/CAMPAIGN_START_SUCCESS',
    CAMPAIGN_START_RESET: 'campaign/CAMPAIGN_START_RESET',

    CAMPAIGN_STOP: 'campaign/CAMPAIGN_STOP',
    CAMPAIGN_STOP_FAILURE: 'campaign/CAMPAIGN_STOP_FAILURE',
    CAMPAIGN_STOP_SUCCESS: 'campaign/CAMPAIGN_STOP_SUCCESS',
    CAMPAIGN_STOP_RESET: 'campaign/CAMPAIGN_STOP_RESET',
};

export default actionType;