const actionType = {
    GET_SETTING: 'setting/GET_SETTING',
    GET_SETTING_FAILURE: 'setting/GET_SETTING_FAILURE',
    GET_SETTING_SUCCESS: 'setting/GET_SETTING_SUCCESS',
    GET_SETTING_RESET: 'setting/GET_SETTING_RESET',

    GET_PROPERTY_SETTINGS: 'setting/GET_PROPERTY_SETTINGS',
    GET_PROPERTY_SETTINGS_SUCCESS: 'setting/GET_PROPERTY_SETTINGS_SUCCESS',
    GET_PROPERTY_SETTINGS_FAILURE: 'setting/GET_PROPERTY_SETTINGS_FAILURE',
    GET_PROPERTY_SETTINGS_RESET: 'setting/GET_PROPERTY_SETTINGS_RESET',

    UPDATE_USER: 'setting/UPDATE_USER',
    UPDATE_USER_FAILURE: 'setting/UPDATE_USER_FAILURE',
    UPDATE_USER_SUCCESS: 'setting/UPDATE_USER_SUCCESS',
    UPDATE_USER_RESET: 'setting/UPDATE_USER_RESET',
};

export default actionType;
