const actionType = {
    GET_SETTING: 'setting/GET_SETTING',
    GET_SETTING_FAILURE: 'setting/GET_SETTING_FAILURE',
    GET_SETTING_SUCCESS: 'setting/GET_SETTING_SUCCESS',
    GET_SETTING_RESET: 'setting/GET_SETTING_RESET',

    GET_PROPERTY_SETTINGS: 'setting/GET_PROPERTY_SETTINGS',
    GET_PROPERTY_SETTINGS_SUCCESS: 'setting/GET_PROPERTY_SETTINGS_SUCCESS',
    GET_PROPERTY_SETTINGS_FAILURE: 'setting/GET_PROPERTY_SETTINGS_FAILURE',
    GET_PROPERTY_SETTINGS_RESET: 'setting/GET_PROPERTY_SETTINGS_RESET',
};

export default actionType;
