const actionType = {
    GET_LEAD: 'lead/GET_LEAD',
    GET_LEAD_FAILURE: 'lead/GET_LEAD_FAILURE',
    GET_LEAD_SUCCESS: 'lead/GET_LEAD_SUCCESS',
    GET_LEAD_RESET: 'lead/GET_LEAD_RESET',

    SAVE_LEAD: 'lead/INS_LEAD',
    SAVE_LEAD_FAILURE: 'lead/INS_LEAD_FAILURE',
    SAVE_LEAD_SUCCESS: 'lead/INS_LEAD_SUCCESS',
    SAVE_LEAD_RESET: 'lead/INS_LEAD_RESET',

    GET_ADVISERS: 'lead/GET_ADVISERS',
    GET_ADVISERS_FAILURE: 'lead/GET_ADVISERS_FAILURE',
    GET_ADVISERS_SUCCESS: 'lead/GET_ADVISERS_SUCCESS',
    GET_ADVISERS_RESET: 'lead/GET_ADVISERS_RESET',

    GET_PHASES: 'lead/GET_PHASES',
    GET_PHASES_FAILURE: 'lead/GET_PHASES_FAILURE',
    GET_PHASES_SUCCESS: 'lead/GET_PHASES_SUCCESS',
    GET_PHASES_RESET: 'lead/GET_PHASES_RESET',

    GET_LEADNOTES: 'lead/GET_LEADNOTES',
    GET_LEADNOTES_FAILURE: 'lead/GET_LEADNOTES_FAILURE',
    GET_LEADNOTES_SUCCESS: 'lead/GET_LEADNOTES_SUCCESS',
    GET_LEADNOTES_RESET: 'lead/GET_LEADNOTES_RESET',

    GET_LEADACTIVITIES: 'lead/GET_LEADACTIVITIES',
    GET_LEADACTIVITIES_FAILURE: 'lead/GET_LEADACTIVITIES_FAILURE',
    GET_LEADACTIVITIES_SUCCESS: 'lead/GET_LEADACTIVITIES_SUCCESS',
    GET_LEADACTIVITIES_RESET: 'lead/GET_LEADACTIVITIES_RESET',

    SAVE_LEADNOIE: 'lead/SAVE_LEADNOIE',
    SAVE_LEADNOIE_FAILURE: 'lead/SAVE_LEADNOIE_FAILURE',
    SAVE_LEADNOIE_SUCCESS: 'lead/SAVE_LEADNOIE_SUCCESS',
    SAVE_LEADNOIE_RESET: 'lead/SAVE_LEADNOIE_RESET',

    SAVE_LEADACTIVITY: 'lead/SAVE_LEADACTIVITY',
    SAVE_LEADACTIVITY_FAILURE: 'lead/SAVE_LEADACTIVITY_FAILURE',
    SAVE_LEADACTIVITY_SUCCESS: 'lead/SAVE_LEADACTIVITY_SUCCESS',
    SAVE_LEADACTIVITY_RESET: 'lead/SAVE_LEADACTIVITY_RESET',

    DISPLAY_LEAD: 'lead/DISPLAY_LEAD',
    DISPLAY_LEAD_RESET: 'lead/DISPLAY_LEAD_RESET',

    ARCHIVE_LEAD: 'lead/ARCHIVE_LEAD',
    ARCHIVE_LEAD_FAILURE: 'lead/ARCHIVE_LEAD_FAILURE',
    ARCHIVE_LEAD_SUCCESS: 'lead/ARCHIVE_LEAD_SUCCESS',
    ARCHIVE_LEAD_RESET: 'lead/ARCHIVE_LEAD_RESET',

    MARK_DONE_ACTIVITY: 'lead/MARK_DONE_ACTIVITY',
    MARK_DONE_ACTIVITY_FAILURE: 'lead/MARK_DONE_ACTIVITY_FAILURE',
    MARK_DONE_ACTIVITY_SUCCESS: 'lead/MARK_DONE_ACTIVITY_SUCCESS',
    MARK_DONE_ACTIVITY_RESET: 'lead/MARK_DONE_ACTIVITY_RESET',

    GET_LEAD_HISTORY: 'lead/GET_LEAD_HISTORY',
    GET_LEAD_HISTORY_FAILURE: 'lead/GET_LEAD_HISTORY_FAILURE',
    GET_LEAD_HISTORY_SUCCESS: 'lead/GET_LEAD_HISTORY_SUCCESS',
    GET_LEAD_HISTORY_RESET: 'lead/GET_LEAD_HISTORY_RESET',

    UPDATE_LEAD_TAGS: 'lead/UPDATE_LEAD_TAGS',
    UPDATE_LEAD_TAGS_FAILURE: 'lead/UPDATE_LEAD_TAGS_FAILURE',
    UPDATE_LEAD_TAGS_SUCCESS: 'lead/UPDATE_LEAD_TAGS_SUCCESS',
    UPDATE_LEAD_TAGS_RESET: 'lead/UPDATE_LEAD_TAGS_RESET',
};

export default actionType;
