const actionType = {
    GET_LEAD: 'lead/GET_LEAD',
    GET_LEAD_FAILURE: 'lead/GET_LEAD_FAILURE',
    GET_LEAD_SUCCESS: 'lead/GET_LEAD_SUCCESS',
    GET_LEAD_RESET: 'lead/GET_LEAD_RESET',

    SAVE_LEAD: 'lead/INS_LEAD',
    SAVE_LEAD_FAILURE: 'lead/INS_LEAD_FAILURE',
    SAVE_LEAD_SUCCESS: 'lead/INS_LEAD_SUCCESS',
    SAVE_LEAD_RESET: 'lead/INS_LEAD_RESET',

    GET_TAGS: 'lead/GET_TAGS',
    GET_TAGS_FAILURE: 'lead/GET_TAGS_FAILURE',
    GET_TAGS_SUCCESS: 'lead/GET_TAGS_SUCCESS',
    GET_TAGS_RESET: 'lead/GET_TAGS_RESET',

    GET_ADVISERS: 'lead/GET_ADVISERS',
    GET_ADVISERS_FAILURE: 'lead/GET_ADVISERS_FAILURE',
    GET_ADVISERS_SUCCESS: 'lead/GET_ADVISERS_SUCCESS',
    GET_ADVISERS_RESET: 'lead/GET_ADVISERS_RESET',
};

export default actionType;
