const actionType = {
    CALENDAR_GOOGLE_RESET: 'calendar/GOOGLE_RESET',
    
    CALENDAR_GOOGLE_LOGIN: 'calendar/GOOGLE_LOGIN',
    CALENDAR_GOOGLE_LOGIN_FAILURE: 'calendar/GOOGLE_LOGIN_FAILURE',
    CALENDAR_GOOGLE_LOGIN_SUCCESS: 'calendar/GOOGLE_LOGIN_SUCCESS',
    CALENDAR_GOOGLE_LOGIN_RESET: 'calendar/GOOGLE_LOGIN_RESET',

    CALENDAR_GOOGLE_DISCONNECT: 'calendar/GOOGLE_DISCONNECT',
    CALENDAR_GOOGLE_DISCONNECT_FAILURE: 'calendar/GOOGLE_DISCONNECT_FAILURE',
    CALENDAR_GOOGLE_DISCONNECT_SUCCESS: 'calendar/GOOGLE_DISCONNECT_SUCCESS',
    CALENDAR_GOOGLE_DISCONNECT_RESET: 'calendar/GOOGLE_DISCONNECT_RESET',

    CALENDAR_GOOGLE_VALIDATE: 'calendar/GOOGLE_VALIDATE',
    CALENDAR_GOOGLE_VALIDATE_FAILURE: 'calendar/GOOGLE_VALIDATE_FAILURE',
    CALENDAR_GOOGLE_VALIDATE_SUCCESS: 'calendar/GOOGLE_VALIDATE_SUCCESS',
    CALENDAR_GOOGLE_VALIDATE_RESET: 'calendar/GOOGLE_VALIDATE_RESET',
};

export default actionType;