const actionType = {
    GET_PERSON: 'person/GET_PERSON',
    GET_PERSON_SUCCESS: 'person/GET_PERSON_SUCCESS',
    GET_PERSON_FAILURE: 'person/GET_PERSON_FAILURE',
    GET_PERSON_RESET: 'person/GET_PERSON_RESET',

    GET_PERSON_LIST: 'person/GET_PERSON_LIST',
    GET_PERSON_LIST_SUCCESS: 'person/GET_PERSON_LIST_SUCCESS',
    GET_PERSON_LIST_FAILURE: 'person/GET_PERSON_LIST_FAILURE',
    GET_PERSON_LIST_RESET: 'person/GET_PERSON_LIST_RESET',

    GET_TICKET_LIST_BY_PERSON: 'person/GET_TICKET_LIST_BY_PERSON',
    GET_TICKET_LIST_BY_PERSON_SUCCESS: 'person/GET_TICKET_LIST_BY_PERSON_SUCCESS',
    GET_TICKET_LIST_BY_PERSON_FAILURE: 'person/GET_TICKET_LIST_BY_PERSON_FAILURE',
    GET_TICKET_LIST_BY_PERSON_RESET: 'person/GET_TICKET_LIST_BY_PERSON_RESET',

    GET_CHANNEL_LIST_BY_PERSON: 'person/GET_CHANNEL_LIST_BY_PERSON',
    GET_CHANNEL_LIST_BY_PERSON_SUCCESS: 'person/GET_CHANNEL_LIST_BY_PERSON_SUCCESS',
    GET_CHANNEL_LIST_BY_PERSON_FAILURE: 'person/GET_CHANNEL_LIST_BY_PERSON_FAILURE',
    GET_CHANNEL_LIST_BY_PERSON_RESET: 'person/GET_CHANNEL_LIST_BY_PERSON_RESET',

    GET_ADDITIONAL_INFO_BY_PERSON: 'person/GET_ADDITIONAL_INFO_BY_PERSON',
    GET_ADDITIONAL_INFO_BY_PERSON_SUCCESS: 'person/GET_ADDITIONAL_INFO_BY_PERSON_SUCCESS',
    GET_ADDITIONAL_INFO_BY_PERSON_FAILURE: 'person/GET_ADDITIONAL_INFO_BY_PERSON_FAILURE',
    GET_ADDITIONAL_INFO_BY_PERSON_RESET: 'person/GET_ADDITIONAL_INFO_BY_PERSON_RESET',

    GET_OPPORTUNITY_LIST_BY_PERSON: 'person/GET_OPPORTUNITY_LIST_BY_PERSON',
    GET_OPPORTUNITY_LIST_BY_PERSON_SUCCESS: 'person/GET_OPPORTUNITY_LIST_BY_PERSON_SUCCESS',
    GET_OPPORTUNITY_LIST_BY_PERSON_FAILURE: 'person/GET_OPPORTUNITY_LIST_BY_PERSON_FAILURE',
    GET_OPPORTUNITY_LIST_BY_PERSON_RESET: 'person/GET_OPPORTUNITY_LIST_BY_PERSON_RESET',
};

export default actionType;
