const actionType = {
    GET_PERSON: 'person/GET_PERSON',
    GET_PERSON_SUCCESS: 'person/GET_PERSON_SUCCESS',
    GET_PERSON_FAILURE: 'person/GET_PERSON_FAILURE',
    GET_PERSON_RESET: 'person/GET_PERSON_RESET',

    GET_PERSON_LIST: 'person/GET_PERSON_LIST',
    GET_PERSON_LIST_SUCCESS: 'person/GET_PERSON_LIST_SUCCESS',
    GET_PERSON_LIST_FAILURE: 'person/GET_PERSON_LIST_FAILURE',
    GET_PERSON_LIST_RESET: 'person/GET_PERSON_LIST_RESET',

    GET_TICKET_LIST_BY_PERSON: 'person/GET_TICKET_LIST_BY_PERSON',
    GET_TICKET_LIST_BY_PERSON_SUCCESS: 'person/GET_TICKET_LIST_BY_PERSON_SUCCESS',
    GET_TICKET_LIST_BY_PERSON_FAILURE: 'person/GET_TICKET_LIST_BY_PERSON_FAILURE',
    GET_TICKET_LIST_BY_PERSON_RESET: 'person/GET_TICKET_LIST_BY_PERSON_RESET',

    GET_REFERRER_LIST_BY_PERSON: 'person/GET_REFERRER_LIST_BY_PERSON',
    GET_REFERRER_LIST_BY_PERSON_SUCCESS: 'person/GET_REFERRER_LIST_BY_PERSON_SUCCESS',
    GET_REFERRER_LIST_BY_PERSON_FAILURE: 'person/GET_REFERRER_LIST_BY_PERSON_FAILURE',
    GET_REFERRER_LIST_BY_PERSON_RESET: 'person/GET_REFERRER_LIST_BY_PERSON_RESET',

    GET_CHANNEL_LIST_BY_PERSON: 'person/GET_CHANNEL_LIST_BY_PERSON',
    GET_CHANNEL_LIST_BY_PERSON_SUCCESS: 'person/GET_CHANNEL_LIST_BY_PERSON_SUCCESS',
    GET_CHANNEL_LIST_BY_PERSON_FAILURE: 'person/GET_CHANNEL_LIST_BY_PERSON_FAILURE',
    GET_CHANNEL_LIST_BY_PERSON_RESET: 'person/GET_CHANNEL_LIST_BY_PERSON_RESET',

    GET_ADDITIONAL_INFO_BY_PERSON: 'person/GET_ADDITIONAL_INFO_BY_PERSON',
    GET_ADDITIONAL_INFO_BY_PERSON_SUCCESS: 'person/GET_ADDITIONAL_INFO_BY_PERSON_SUCCESS',
    GET_ADDITIONAL_INFO_BY_PERSON_FAILURE: 'person/GET_ADDITIONAL_INFO_BY_PERSON_FAILURE',
    GET_ADDITIONAL_INFO_BY_PERSON_RESET: 'person/GET_ADDITIONAL_INFO_BY_PERSON_RESET',

    GET_LEAD_LIST_BY_PERSON: 'person/GET_LEAD_LIST_BY_PERSON',
    GET_LEAD_LIST_BY_PERSON_SUCCESS: 'person/GET_LEAD_LIST_BY_PERSON_SUCCESS',
    GET_LEAD_LIST_BY_PERSON_FAILURE: 'person/GET_LEAD_LIST_BY_PERSON_FAILURE',
    GET_LEAD_LIST_BY_PERSON_RESET: 'person/GET_LEAD_LIST_BY_PERSON_RESET',

    GET_DOMAINS_BY_TYPENAME: 'person/GET_DOMAINS_BY_TYPENAME',
    GET_DOMAINS_BY_TYPENAME_SUCCESS: 'person/GET_DOMAINS_BY_TYPENAME_SUCCESS',
    GET_DOMAINS_BY_TYPENAME_FAILURE: 'person/GET_DOMAINS_BY_TYPENAME_FAILURE',
    GET_DOMAINS_BY_TYPENAME_RESET: 'person/GET_DOMAINS_BY_TYPENAME_RESET',

    EDIT_PERSON: 'person/EDIT_PERSON',
    EDIT_PERSON_SUCCESS: 'person/EDIT_PERSON_SUCCESS',
    EDIT_PERSON_FAILURE: 'person/EDIT_PERSON_FAILURE',
    EDIT_PERSON_RESET: 'person/EDIT_PERSON_RESET',
};

export default actionType;
