const actionType = {
    TESTMESSAGE_SEND: 'witai/REQUEST_SEND',
    TESTMESSAGE_FAILURE: 'witai/REQUEST_FAILURE',
    TESTMESSAGE_SUCCESS: 'witai/REQUEST_SUCCESS',
    TESTMESSAGE_RESET: 'witai/REQUEST_RESET',
    TRAINMODEL_SEND: 'witai/TRAINMODEL_SEND',
    TRAINMODEL_FAILURE: 'witai/TRAINMODEL_FAILURE',
    TRAINMODEL_SUCCESS: 'witai/TRAINMODEL_SUCCESS',
    TRAINMODEL_RESET: 'witai/TRAINMODEL_RESET',

    OPERATIONPOST_SEND: 'witai/OPERATIONPOST_SEND',
    OPERATIONPOST_FAILURE: 'witai/OPERATIONPOST_FAILURE',
    OPERATIONPOST_SUCCESS: 'witai/OPERATIONPOST_SUCCESS',
    RESETOPERATIONRESULT: 'witai/RESETOPERATIONRESULT',
};

export default actionType;