const actionType = {
    PAYMENT_NIUBIZ_AUTHORIZETRANSACTION: 'payment/PAYMENT_NIUBIZ_AUTHORIZETRANSACTION',
    PAYMENT_NIUBIZ_AUTHORIZETRANSACTION_FAILURE: 'payment/PAYMENT_NIUBIZ_AUTHORIZETRANSACTION_FAILURE',
    PAYMENT_NIUBIZ_AUTHORIZETRANSACTION_SUCCESS: 'payment/PAYMENT_NIUBIZ_AUTHORIZETRANSACTION_SUCCESS',
    PAYMENT_NIUBIZ_AUTHORIZETRANSACTION_RESET: 'payment/PAYMENT_NIUBIZ_AUTHORIZETRANSACTION_RESET',

    PAYMENT_NIUBIZ_CREATESESSIONTOKEN: 'payment/PAYMENT_NIUBIZ_CREATESESSIONTOKEN',
    PAYMENT_NIUBIZ_CREATESESSIONTOKEN_FAILURE: 'payment/PAYMENT_NIUBIZ_CREATESESSIONTOKEN_FAILURE',
    PAYMENT_NIUBIZ_CREATESESSIONTOKEN_SUCCESS: 'payment/PAYMENT_NIUBIZ_CREATESESSIONTOKEN_SUCCESS',
    PAYMENT_NIUBIZ_CREATESESSIONTOKEN_RESET: 'payment/PAYMENT_NIUBIZ_CREATESESSIONTOKEN_RESET',
};

export default actionType;