const actionType = {
    PAYMENT_NIUBIZ_AUTHORIZETRANSACTION: 'payment/PAYMENT_NIUBIZ_AUTHORIZETRANSACTION',
    PAYMENT_NIUBIZ_AUTHORIZETRANSACTION_FAILURE: 'payment/PAYMENT_NIUBIZ_AUTHORIZETRANSACTION_FAILURE',
    PAYMENT_NIUBIZ_AUTHORIZETRANSACTION_SUCCESS: 'payment/PAYMENT_NIUBIZ_AUTHORIZETRANSACTION_SUCCESS',
    PAYMENT_NIUBIZ_AUTHORIZETRANSACTION_RESET: 'payment/PAYMENT_NIUBIZ_AUTHORIZETRANSACTION_RESET',

    PAYMENT_NIUBIZ_CREATESESSIONTOKEN: 'payment/PAYMENT_NIUBIZ_CREATESESSIONTOKEN',
    PAYMENT_NIUBIZ_CREATESESSIONTOKEN_FAILURE: 'payment/PAYMENT_NIUBIZ_CREATESESSIONTOKEN_FAILURE',
    PAYMENT_NIUBIZ_CREATESESSIONTOKEN_SUCCESS: 'payment/PAYMENT_NIUBIZ_CREATESESSIONTOKEN_SUCCESS',
    PAYMENT_NIUBIZ_CREATESESSIONTOKEN_RESET: 'payment/PAYMENT_NIUBIZ_CREATESESSIONTOKEN_RESET',

    PAYMENT_OPENPAY_GETPAYMENTORDER: 'payment/PAYMENT_OPENPAY_GETPAYMENTORDER',
    PAYMENT_OPENPAY_GETPAYMENTORDER_FAILURE: 'payment/PAYMENT_OPENPAY_GETPAYMENTORDER_FAILURE',
    PAYMENT_OPENPAY_GETPAYMENTORDER_SUCCESS: 'payment/PAYMENT_OPENPAY_GETPAYMENTORDER_SUCCESS',
    PAYMENT_OPENPAY_GETPAYMENTORDER_RESET: 'payment/PAYMENT_OPENPAY_GETPAYMENTORDER_RESET',

    PAYMENT_OPENPAY_PROCESSTRANSACTION: 'payment/PAYMENT_OPENPAY_PROCESSTRANSACTION',
    PAYMENT_OPENPAY_PROCESSTRANSACTION_FAILURE: 'payment/PAYMENT_OPENPAY_PROCESSTRANSACTION_FAILURE',
    PAYMENT_OPENPAY_PROCESSTRANSACTION_SUCCESS: 'payment/PAYMENT_OPENPAY_PROCESSTRANSACTION_SUCCESS',
    PAYMENT_OPENPAY_PROCESSTRANSACTION_RESET: 'payment/PAYMENT_OPENPAY_PROCESSTRANSACTION_RESET',
};

export default actionType;