const actionType = {
    RECOVER_PASSWORD: 'subscription/RECOVER_PASSWORD',
    RECOVER_PASSWORD_FAILURE: 'subscription/RECOVER_PASSWORD_FAILURE',
    RECOVER_PASSWORD_RESET: 'subscription/RECOVER_PASSWORD_RESET',
    RECOVER_PASSWORD_SUCCESS: 'subscription/RECOVER_PASSWORD_SUCCESS',

    CHANGE_PASSWORD: 'subscription/CHANGE_PASSWORD',
    CHANGE_PASSWORD_FAILURE: 'subscription/CHANGE_PASSWORD_FAILURE',
    CHANGE_PASSWORD_RESET: 'subscription/CHANGE_PASSWORD_RESET',
    CHANGE_PASSWORD_SUCCESS: 'subscription/CHANGE_PASSWORD_SUCCESS',

    VALIDATE_CHANNELS: 'subscription/VALIDATE_CHANNELS',
    VALIDATE_CHANNELS_FAILURE: 'subscription/VALIDATE_CHANNELS_FAILURE',
    VALIDATE_CHANNELS_RESET: 'subscription/VALIDATE_CHANNELS_RESET',
    VALIDATE_CHANNELS_SUCCESS: 'subscription/VALIDATE_CHANNELS_SUCCESS',
};

export default actionType;