const actionType = {
    EXCHANGE_CODE: 'voximplant/EXCHANGE_CODE',
    EXCHANGE_CODE_FAILURE: 'voximplant/EXCHANGE_CODE_FAILURE',
    EXCHANGE_CODE_SUCCESS: 'voximplant/EXCHANGE_CODE_SUCCESS',
    EXCHANGE_CODE_RESET: 'voximplant/EXCHANGE_CODE_RESET',

    LIST_BLOGGER: 'voximplant/LIST_BLOGGER',
    LIST_BLOGGER_FAILURE: 'voximplant/LIST_BLOGGER_FAILURE',
    LIST_BLOGGER_SUCCESS: 'voximplant/LIST_BLOGGER_SUCCESS',
    LIST_BLOGGER_RESET: 'voximplant/LIST_BLOGGER_RESET',

    LIST_YOUTUBE: 'voximplant/LIST_YOUTUBE',
    LIST_YOUTUBE_FAILURE: 'voximplant/LIST_YOUTUBE_FAILURE',
    LIST_YOUTUBE_SUCCESS: 'voximplant/LIST_YOUTUBE_SUCCESS',
    LIST_YOUTUBE_RESET: 'voximplant/LIST_YOUTUBE_RESET',
};

export default actionType;