const ENV = import.meta.env.VITE_ENV || 'TESTING';

const APIS_URL: Record<string, Record<string, string | boolean>> = {
    DEVELOP: {
        API: 'https://apix.laraigo.com/api',
        //WS: 'http://localhost:7070',
        WS: 'https://socket.laraigo.com',
        CHATFLOW: 'https://zyxmelinux2.zyxmeapp.com/zyxme/chatflow',
        FACEBOOKAPP: '235008923608113',
        FACEBOOKAPPLEAD: '278694331357045',
        APIKEY_GMAPS: "AIzaSyAqrFCH95Tbqwo6opvVPcdtrVd-1fnBLr4",
        APIKEY_GC: "AIzaSyD4SpzcUXvxMyj3GS45Dntt8sMdmq2BDcQ",
        INSTAGRAMAPP: '467230660781510',
        CATALOGAPP: '2131127810437236',
        CULQIKEY: 'pk_test_041501e753dcb2f9',
        GOOGLECLIENTID_LOGIN: '283248303891-t9r3irs0rhpsd1pense45mvldesd4bbv.apps.googleusercontent.com',
        GOOGLECLIENTID_CHANNEL: '129996056340-5spevp6sdv32c8dpbf9vhbfjjpvfqrth.apps.googleusercontent.com',
        FACEBOOKVERSION: 'v19.0',
        DIALOG360PARTNERID: 'nPJXndPA',
        GOOGLECLIENTID_CALENDAR: '283248303891-7kttlq9tn5f43bk821fg7lnbhj5hvf6b.apps.googleusercontent.com',
        WEBFORMCHANNEL_FORM: 'https://staticfileszyxme.s3.us-east.cloud-object-storage.appdomain.cloud/anonymous/static/test-FormWebClient.min.js',
        USELARAIGO: false,
        BODEGAACME: true,
        OPENPAYSANDBOX: true,
    },
    TESTING: {
        API: 'https://testapix.laraigo.com/api',
        WS: 'https://testsocket.laraigo.com',
        CHATFLOW: 'https://zyxmelinux2.zyxmeapp.com/zyxmetest/chatflow',
        FACEBOOKAPP: '1094526090706564',
        FACEBOOKAPPLEAD: '278694331357045',
        APIKEY_GMAPS: "AIzaSyAqrFCH95Tbqwo6opvVPcdtrVd-1fnBLr4",
        APIKEY_GC: "AIzaSyD4SpzcUXvxMyj3GS45Dntt8sMdmq2BDcQ",
        INSTAGRAMAPP: '1872023336244866',
        CATALOGAPP: '2131127810437236',
        CULQIKEY: 'pk_test_041501e753dcb2f9',
        GOOGLECLIENTID_LOGIN: '283248303891-t9r3irs0rhpsd1pense45mvldesd4bbv.apps.googleusercontent.com',
        GOOGLECLIENTID_CHANNEL: '129996056340-5spevp6sdv32c8dpbf9vhbfjjpvfqrth.apps.googleusercontent.com',
        FACEBOOKVERSION: 'v19.0',
        DIALOG360PARTNERID: 'nPJXndPA',
        GOOGLECLIENTID_CALENDAR: '283248303891-7kttlq9tn5f43bk821fg7lnbhj5hvf6b.apps.googleusercontent.com',
        WEBFORMCHANNEL_FORM: 'https://staticfileszyxme.s3.us-east.cloud-object-storage.appdomain.cloud/anonymous/static/testing-form.min.js',
        USELARAIGO: false,
        BODEGAACME: true,
        OPENPAYSANDBOX: true,
    },
    PRODUCTION: {
        API: 'https://apiprd.laraigo.com/api',
        WS: 'https://broker.laraigo.com',
        CHATFLOW: 'https://chatflow.s3-web.us-east.cloud-object-storage.appdomain.cloud',
        FACEBOOKAPP: '1980305408682607',
        FACEBOOKAPPLEAD: '278694331357045',
        APIKEY_GMAPS: "AIzaSyAqrFCH95Tbqwo6opvVPcdtrVd-1fnBLr4",
        APIKEY_GC: "AIzaSyD4SpzcUXvxMyj3GS45Dntt8sMdmq2BDcQ",
        INSTAGRAMAPP: '1924971937716955',
        CATALOGAPP: '2131127810437236',
        CULQIKEY: 'pk_test_041501e753dcb2f9',
        GOOGLECLIENTID_LOGIN: '283248303891-t9r3irs0rhpsd1pense45mvldesd4bbv.apps.googleusercontent.com',
        GOOGLECLIENTID_CHANNEL: '129996056340-5spevp6sdv32c8dpbf9vhbfjjpvfqrth.apps.googleusercontent.com',
        FACEBOOKVERSION: 'v19.0',
        DIALOG360PARTNERID: 'nPJXndPA',
        GOOGLECLIENTID_CALENDAR: '283248303891-7kttlq9tn5f43bk821fg7lnbhj5hvf6b.apps.googleusercontent.com',
        WEBFORMCHANNEL_FORM: 'https://staticfileszyxme.s3.us-east.cloud-object-storage.appdomain.cloud/anonymous/static/production-form.min.js',
        USELARAIGO: true,
        BODEGAACME: false,
        OPENPAYSANDBOX: false,
    },
    STAGING: {
        API: 'https://stagingapi.laraigo.com/api',
        WS: 'https://stagingsocket.laraigo.com',
        CHATFLOW: 'https://chatflow-staging.s3-web.us-south.cloud-object-storage.appdomain.cloud',
        FACEBOOKAPP: '1980305408682607',
        FACEBOOKAPPLEAD: '278694331357045',
        APIKEY_GMAPS: "AIzaSyAqrFCH95Tbqwo6opvVPcdtrVd-1fnBLr4",
        INSTAGRAMAPP: '1924971937716955',
        CATALOGAPP: '2131127810437236',
        CULQIKEY: 'pk_test_041501e753dcb2f9',
        GOOGLECLIENTID_LOGIN: '283248303891-t9r3irs0rhpsd1pense45mvldesd4bbv.apps.googleusercontent.com',
        GOOGLECLIENTID_CHANNEL: '129996056340-5spevp6sdv32c8dpbf9vhbfjjpvfqrth.apps.googleusercontent.com',
        FACEBOOKVERSION: 'v19.0',
        DIALOG360PARTNERID: 'nPJXndPA',
        GOOGLECLIENTID_CALENDAR: '283248303891-7kttlq9tn5f43bk821fg7lnbhj5hvf6b.apps.googleusercontent.com',
        WEBFORMCHANNEL_FORM: 'https://staticfileszyxme.s3.us-east.cloud-object-storage.appdomain.cloud/anonymous/static/production-form.min.js',
        USELARAIGO: true,
        BODEGAACME: false,
        OPENPAYSANDBOX: false,
    },
    MARKETING: {
        API: 'https://apimarketing.laraigo.com/api',
        WS: 'https://brokermarketing.laraigo.com',
        CHATFLOW: 'https://chatflow-marketing.s3-web.us-east.cloud-object-storage.appdomain.cloud',
        FACEBOOKAPP: '1980305408682607',
        FACEBOOKAPPLEAD: '278694331357045',
        APIKEY_GMAPS: "AIzaSyAqrFCH95Tbqwo6opvVPcdtrVd-1fnBLr4",
        APIKEY_GC: "AIzaSyD4SpzcUXvxMyj3GS45Dntt8sMdmq2BDcQ",
        INSTAGRAMAPP: '1924971937716955',
        CATALOGAPP: '2131127810437236',
        CULQIKEY: 'pk_test_041501e753dcb2f9',
        GOOGLECLIENTID_LOGIN: '283248303891-t9r3irs0rhpsd1pense45mvldesd4bbv.apps.googleusercontent.com',
        GOOGLECLIENTID_CHANNEL: '129996056340-5spevp6sdv32c8dpbf9vhbfjjpvfqrth.apps.googleusercontent.com',
        FACEBOOKVERSION: 'v19.0',
        DIALOG360PARTNERID: 'nPJXndPA',
        GOOGLECLIENTID_CALENDAR: '283248303891-7kttlq9tn5f43bk821fg7lnbhj5hvf6b.apps.googleusercontent.com',
        WEBFORMCHANNEL_FORM: 'https://staticfileszyxme.s3.us-east.cloud-object-storage.appdomain.cloud/anonymous/static/production-form.min.js',
        USELARAIGO: true,
        BODEGAACME: false,
        OPENPAYSANDBOX: false,
    },
    INCREMENTAL_PROD: {
        API: 'https://api-historical-publico.laraigo.com/api',
        WS: 'https://socket.laraigo.com',
        CHATFLOW: 'https://chatflow.s3-web.us-east.cloud-object-storage.appdomain.cloud',
        FACEBOOKAPP: '1980305408682607',
        FACEBOOKAPPLEAD: '278694331357045',
        APIKEY_GMAPS: "AIzaSyAqrFCH95Tbqwo6opvVPcdtrVd-1fnBLr4",
        APIKEY_GC: "AIzaSyD4SpzcUXvxMyj3GS45Dntt8sMdmq2BDcQ",
        INSTAGRAMAPP: '1924971937716955',
        CATALOGAPP: '2131127810437236',
        CULQIKEY: 'pk_test_041501e753dcb2f9',
        GOOGLECLIENTID_LOGIN: '283248303891-t9r3irs0rhpsd1pense45mvldesd4bbv.apps.googleusercontent.com',
        GOOGLECLIENTID_CHANNEL: '129996056340-5spevp6sdv32c8dpbf9vhbfjjpvfqrth.apps.googleusercontent.com',
        FACEBOOKVERSION: 'v19.0',
        DIALOG360PARTNERID: 'nPJXndPA',
        GOOGLECLIENTID_CALENDAR: '283248303891-7kttlq9tn5f43bk821fg7lnbhj5hvf6b.apps.googleusercontent.com',
        WEBFORMCHANNEL_FORM: 'https://staticfileszyxme.s3.us-east.cloud-object-storage.appdomain.cloud/anonymous/static/production-form.min.js',
        USELARAIGO: true,
        BODEGAACME: false,
        OPENPAYSANDBOX: false,
    },
    INCREMENTAL_CLARO: {
        API: 'https://api-historical-claro.laraigo.com/api',
        WS: 'https://socket.laraigo.com',
        CHATFLOW: 'https://chatflow.s3-web.us-east.cloud-object-storage.appdomain.cloud',
        FACEBOOKAPP: '1980305408682607',
        FACEBOOKAPPLEAD: '278694331357045',
        APIKEY_GMAPS: "AIzaSyAqrFCH95Tbqwo6opvVPcdtrVd-1fnBLr4",
        APIKEY_GC: "AIzaSyD4SpzcUXvxMyj3GS45Dntt8sMdmq2BDcQ",
        INSTAGRAMAPP: '1924971937716955',
        CATALOGAPP: '2131127810437236',
        CULQIKEY: 'pk_test_041501e753dcb2f9',
        GOOGLECLIENTID_LOGIN: '283248303891-t9r3irs0rhpsd1pense45mvldesd4bbv.apps.googleusercontent.com',
        GOOGLECLIENTID_CHANNEL: '129996056340-5spevp6sdv32c8dpbf9vhbfjjpvfqrth.apps.googleusercontent.com',
        FACEBOOKVERSION: 'v19.0',
        DIALOG360PARTNERID: 'nPJXndPA',
        GOOGLECLIENTID_CALENDAR: '283248303891-7kttlq9tn5f43bk821fg7lnbhj5hvf6b.apps.googleusercontent.com',
        WEBFORMCHANNEL_FORM: 'https://staticfileszyxme.s3.us-east.cloud-object-storage.appdomain.cloud/anonymous/static/production-form.min.js',
        USELARAIGO: true,
        BODEGAACME: false,
        OPENPAYSANDBOX: false,
    },
    CLARO: {
        API: 'https://claroapi.laraigo.com/api',
        WS: 'https://clarobroker.laraigo.com',
        CHATFLOW: 'https://chatflow-claro.s3-web.us-east.cloud-object-storage.appdomain.cloud',
        FACEBOOKAPP: '1980305408682607',
        FACEBOOKAPPLEAD: '278694331357045',
        APIKEY_GMAPS: "AIzaSyCDfPhg86YSt25QynLajl7GA5Ux6YEphoA",
        APIKEY_GC: "AIzaSyD4SpzcUXvxMyj3GS45Dntt8sMdmq2BDcQ",
        INSTAGRAMAPP: '1924971937716955',
        CATALOGAPP: '2131127810437236',
        CULQIKEY: 'pk_test_041501e753dcb2f9',
        GOOGLECLIENTID_LOGIN: '283248303891-t9r3irs0rhpsd1pense45mvldesd4bbv.apps.googleusercontent.com',
        GOOGLECLIENTID_CHANNEL: '129996056340-5spevp6sdv32c8dpbf9vhbfjjpvfqrth.apps.googleusercontent.com',
        FACEBOOKVERSION: 'v19.0',
        DIALOG360PARTNERID: 'nPJXndPA',
        GOOGLECLIENTID_CALENDAR: '283248303891-7kttlq9tn5f43bk821fg7lnbhj5hvf6b.apps.googleusercontent.com',
        WEBFORMCHANNEL_FORM: 'https://staticfileszyxme.s3.us-east.cloud-object-storage.appdomain.cloud/anonymous/static/production-form.min.js',
        USELARAIGO: true,
        BODEGAACME: false,
        OPENPAYSANDBOX: false,
    },
    CLAROHISTORICAL: {
        API: 'http://10.240.65.10:6066/api',
        WS: 'https://clarobroker.laraigo.com',
        CHATFLOW: 'https://chatflow-claro.s3-web.us-east.cloud-object-storage.appdomain.cloud',
        FACEBOOKAPP: '1980305408682607',
        FACEBOOKAPPLEAD: '278694331357045',
        APIKEY_GMAPS: "AIzaSyAqrFCH95Tbqwo6opvVPcdtrVd-1fnBLr4",
        APIKEY_GC: "AIzaSyD4SpzcUXvxMyj3GS45Dntt8sMdmq2BDcQ",
        INSTAGRAMAPP: '1924971937716955',
        CATALOGAPP: '2131127810437236',
        CULQIKEY: 'pk_test_041501e753dcb2f9',
        GOOGLECLIENTID_LOGIN: '283248303891-t9r3irs0rhpsd1pense45mvldesd4bbv.apps.googleusercontent.com',
        GOOGLECLIENTID_CHANNEL: '129996056340-5spevp6sdv32c8dpbf9vhbfjjpvfqrth.apps.googleusercontent.com',
        FACEBOOKVERSION: 'v19.0',
        DIALOG360PARTNERID: 'nPJXndPA',
        GOOGLECLIENTID_CALENDAR: '283248303891-7kttlq9tn5f43bk821fg7lnbhj5hvf6b.apps.googleusercontent.com',
        USELARAIGO: true,
        BODEGAACME: false,
        OPENPAYSANDBOX: false,
    },
    CLOUD: {
        API: 'https://cloudapi.laraigo.com/api',
        WS: 'https://cloudbroker.laraigo.com',
        CHATFLOW: 'https://zyxmelinux2.zyxmeapp.com/zyxmedemo/chatflowcloud',
        FACEBOOKAPP: '235008923608113',
        FACEBOOKAPPLEAD: '278694331357045',
        APIKEY_GMAPS: "AIzaSyAqrFCH95Tbqwo6opvVPcdtrVd-1fnBLr4",
        APIKEY_GC: "AIzaSyD4SpzcUXvxMyj3GS45Dntt8sMdmq2BDcQ",
        INSTAGRAMAPP: '467230660781510',
        CATALOGAPP: '2131127810437236',
        CULQIKEY: 'pk_test_041501e753dcb2f9',
        GOOGLECLIENTID_LOGIN: '283248303891-t9r3irs0rhpsd1pense45mvldesd4bbv.apps.googleusercontent.com',
        GOOGLECLIENTID_CHANNEL: '129996056340-5spevp6sdv32c8dpbf9vhbfjjpvfqrth.apps.googleusercontent.com',
        FACEBOOKVERSION: 'v19.0',
        DIALOG360PARTNERID: 'nPJXndPA',
        GOOGLECLIENTID_CALENDAR: '283248303891-7kttlq9tn5f43bk821fg7lnbhj5hvf6b.apps.googleusercontent.com',
        WEBFORMCHANNEL_FORM: 'https://staticfileszyxme.s3.us-east.cloud-object-storage.appdomain.cloud/anonymous/static/production-form.min.js',
        USELARAIGO: false,
        BODEGAACME: true,
        OPENPAYSANDBOX: true,
    },
    DEMO: {
        API: 'https://demoapix.laraigo.com/api',
        WS: 'https://demosocket.laraigo.com',
        CHATFLOW: 'https://zyxmelinux2.zyxmeapp.com/zyxmedemo/chatflow',
        FACEBOOKAPP: '235008923608113',
        FACEBOOKAPPLEAD: '278694331357045',
        APIKEY_GMAPS: "AIzaSyAqrFCH95Tbqwo6opvVPcdtrVd-1fnBLr4",
        APIKEY_GC: "AIzaSyD4SpzcUXvxMyj3GS45Dntt8sMdmq2BDcQ",
        INSTAGRAMAPP: '467230660781510',
        CATALOGAPP: '2131127810437236',
        CULQIKEY: 'pk_test_041501e753dcb2f9',
        GOOGLECLIENTID_LOGIN: '283248303891-t9r3irs0rhpsd1pense45mvldesd4bbv.apps.googleusercontent.com',
        GOOGLECLIENTID_CHANNEL: '129996056340-5spevp6sdv32c8dpbf9vhbfjjpvfqrth.apps.googleusercontent.com',
        FACEBOOKVERSION: 'v19.0',
        DIALOG360PARTNERID: 'nPJXndPA',
        GOOGLECLIENTID_CALENDAR: '283248303891-7kttlq9tn5f43bk821fg7lnbhj5hvf6b.apps.googleusercontent.com',
        WEBFORMCHANNEL_FORM: 'https://staticfileszyxme.s3.us-east.cloud-object-storage.appdomain.cloud/anonymous/static/production-form.min.js',
        USELARAIGO: false,
        BODEGAACME: true,
        OPENPAYSANDBOX: true,
    },
    LOCAL: {
        API: 'http://localhost:6065/api',
        //API: 'https://apix.laraigo.com/api',
        WS: 'https://socket.laraigo.com',
        //WS: 'http://localhost:7070',
        CHATFLOW: 'https://zyxmelinux2.zyxmeapp.com/zyxme/chatflow',
        FACEBOOKAPP: '235008923608113',
        FACEBOOKAPPLEAD: '278694331357045',
        APIKEY_GMAPS: "AIzaSyAqrFCH95Tbqwo6opvVPcdtrVd-1fnBLr4",
        APIKEY_GC: "AIzaSyD4SpzcUXvxMyj3GS45Dntt8sMdmq2BDcQ",
        INSTAGRAMAPP: '467230660781510',
        CATALOGAPP: '2131127810437236',
        CULQIKEY: 'pk_test_041501e753dcb2f9',
        GOOGLECLIENTID_LOGIN: '283248303891-t9r3irs0rhpsd1pense45mvldesd4bbv.apps.googleusercontent.com',
        GOOGLECLIENTID_CHANNEL: '129996056340-5spevp6sdv32c8dpbf9vhbfjjpvfqrth.apps.googleusercontent.com',
        FACEBOOKVERSION: 'v19.0',
        DIALOG360PARTNERID: 'nPJXndPA',
        GOOGLECLIENTID_CALENDAR: '283248303891-7kttlq9tn5f43bk821fg7lnbhj5hvf6b.apps.googleusercontent.com',
        WEBFORMCHANNEL_FORM: 'https://staticfileszyxme.s3.us-east.cloud-object-storage.appdomain.cloud/anonymous/static/test-FormWebClient.min.js',
        USELARAIGO: false,
        BODEGAACME: true,
        OPENPAYSANDBOX: true,
    }
}

const BASE_URL = APIS_URL[ENV].API
const WS_URL = APIS_URL[ENV].WS
const CHATFLOW_URL = APIS_URL[ENV].CHATFLOW
const FACEBOOKAPP = APIS_URL[ENV].FACEBOOKAPP
const FACEBOOKAPPLEAD = APIS_URL[ENV].FACEBOOKAPPLEAD
const INSTAGRAMAPP = APIS_URL[ENV].INSTAGRAMAPP
const CATALOGAPP = APIS_URL[ENV].CATALOGAPP
const CULQIKEY = APIS_URL[ENV].CULQIKEY
const GOOGLECLIENTID_LOGIN = APIS_URL[ENV].GOOGLECLIENTID_LOGIN
const GOOGLECLIENTID_CHANNEL = APIS_URL[ENV].GOOGLECLIENTID_CHANNEL
const FACEBOOKVERSION = APIS_URL[ENV].FACEBOOKVERSION
const DIALOG360PARTNERID = APIS_URL[ENV].DIALOG360PARTNERID
const GOOGLECLIENTID_CALENDAR = APIS_URL[ENV].GOOGLECLIENTID_CALENDAR
const WEBFORMCHANNEL_FORM = APIS_URL[ENV].WEBFORMCHANNEL_FORM
const APIKEY_GMAPS = APIS_URL[ENV].APIKEY_GMAPS
const APIKEY_GC = APIS_URL[ENV].APIKEY_GC
const USELARAIGO = APIS_URL[ENV].USELARAIGO
const BODEGAACME = APIS_URL[ENV].BODEGAACME
const OPENPAYSANDBOX = APIS_URL[ENV].OPENPAYSANDBOX

export const apiUrls = {
    WS_URL,
    FACEBOOKAPP,
    FACEBOOKAPPLEAD,
    INSTAGRAMAPP,
    CATALOGAPP,
    CULQIKEY,
    GOOGLECLIENTID_LOGIN,
    GOOGLECLIENTID_CHANNEL,
    FACEBOOKVERSION,
    DIALOG360PARTNERID,
    GOOGLECLIENTID_CALENDAR,
    WEBFORMCHANNEL_FORM,
    APIKEY_GMAPS,
    APIKEY_GC,
    USELARAIGO,
    BODEGAACME,
    OPENPAYSANDBOX,

    LOGIN_URL: `${BASE_URL}/auth`,
    CONNECT_INBOX: `${BASE_URL}/auth/connect`,
    INVOKE_INCREMENTAL: `${BASE_URL}/auth/incremental/invoke/token`,
    CHANGE_ORGANIZATION: `${BASE_URL}/auth/changeorganization`,
    LOGOUT_URL: `${BASE_URL}/auth/logout`,
    MAIN_URL: `${BASE_URL}/main`,
    MAIN_EVENT_BOOKING_URL: `${BASE_URL}/event-booking/collection`,
    MAIN_EVENT_CANCELBOOKING_URL: `${BASE_URL}/event-booking/canceleventlaraigo`,
    MAIN_URL_PUBLIC: `${BASE_URL}/main/public/domainvalues`,
    MAIN_URL_PAYMENTORDER: `${BASE_URL}/main/public/paymentorder`,
    MAIN_URL_PAYMENTORDERNIUBIZ: `${BASE_URL}/main/public/paymentorderniubiz`,
    MAIN_URL_PAYMENTORDEROPENPAY: `${BASE_URL}/main/public/paymentorderopenpay`,
    MAIN_URL_PAYMENTORDEROPENPAYCOLOMBIA: `${BASE_URL}/main/public/paymentorderopenpaycolombia`,
    MAIN_URL_PAYMENTORDERIZIPAY: `${BASE_URL}/main/public/paymentorderizipay`,
    MAIN_URL_PAYMENTORDEREPAYCO: `${BASE_URL}/main/public/paymentorderepayco`,
    MAIN_URL_PHONEREDIRECT: `${BASE_URL}/main/public/phoneredirect`,
    MAIN_MULTI: `${BASE_URL}/main/multi`,
    MAIN_MULTI_PUBLIC: `${BASE_URL}/main/public/multi/domainvalues`,
    EXECUTE_TRANSACTION: `${BASE_URL}/main/executetransaction`,
    MAIN_PAGINATED: `${BASE_URL}/main/paginated`,
    MAIN_GRAPHIC: `${BASE_URL}/main/graphic`,
    MAIN_DYNAMIC: `${BASE_URL}/reportdesigner`,
    MAIN_DYNAMIC_EXPORT: `${BASE_URL}/reportdesigner/export`,
    INTEGRATION: `${BASE_URL}/integration`,
    UPLOAD_FILE: `${BASE_URL}/upload`,
    TEST_REQUEST: `${BASE_URL}/flow/testrequest`,
    UPLOAD_FILEMETADATA: `${BASE_URL}/upload/metadata`,
    EXPORT_DATA: `${BASE_URL}/main/export`,

    CLOSE_TICKET: `${BASE_URL}/ticket/close`,
    MASSIVE_CLOSE_TICKET: `${BASE_URL}/ticket/massiveclose`,
    REPLY_TICKET: `${BASE_URL}/ticket/reply`,
    REPLY_LIST_TICKET: `${BASE_URL}/ticket/reply/list`,
    REASSIGN_TICKET: `${BASE_URL}/ticket/reassign`,
    SEND_HSM: `${BASE_URL}/ticket/send/hsm`,
    IMPORT_TICKET: `${BASE_URL}/ticket/import`,
    UPDATE_USER: `${BASE_URL}/user/update/info`,
    SAVE_USER: `${BASE_URL}/user/sendmail/password`,
    DEL_USER: `${BASE_URL}/user/delete`,
    WITAITEST: `${BASE_URL}/witai/message`,
    WITAITRAIN: `${BASE_URL}/witai/train_model`,
    WITAIENTITYINS: `${BASE_URL}/witai/entity`,
    WITAIUTTERANCEINS: `${BASE_URL}/witai/intent_utterance`,
    WITAIINTENTDEL: `${BASE_URL}/witai/intent_del`,
    WITAIENTITYDEL: `${BASE_URL}/witai/entity_del`,
    WITAIENTITYIMPORT: `${BASE_URL}/witai/entity_import`,
    WITAIINTENTIMPORT: `${BASE_URL}/witai/intent_import`,
    GETGEOCODE: `${BASE_URL}/gmaps/geocode`,
    GETLOCATION: `${BASE_URL}/flow/location`,
    GETVERSION: `${BASE_URL}/check/version`,
    TRIGGERBLOCK: `${BASE_URL}/flow/triggerblock`,
    WATSONTESTINT: `${BASE_URL}/watson/tryit`,
    WATSONMENTION: `${BASE_URL}/watson/mention`,
    WATSONSYNC: `${BASE_URL}/watson/sync`,
    WATSONBULKLOAD: `${BASE_URL}/watson/bulkload`,
    WATSONCONFLICTRESOLVE: `${BASE_URL}/watson/conflicts/resolve`,
    WATSONINTENT: `${BASE_URL}/watson/intent`,
    WATSONENTITY: `${BASE_URL}/watson/entity`,
    WATSONITEMDELETE: `${BASE_URL}/watson/item/delete`,
    RASATESTINT: `${BASE_URL}/rasa/test`,
    RASATRAININT: `${BASE_URL}/rasa/train`,
    RASADOWNLOADINT: `${BASE_URL}/rasa/download`,
    RASAUPLOADINT: `${BASE_URL}/rasa/upload`,
    RASAMODELLIST: `${BASE_URL}/rasa/list`,
    RASAMODELDOWNLOAD: `${BASE_URL}/rasa/download-model`,
    GENERATE_APIKEY: `${BASE_URL}/user/generatetoken`,
    INTEGRATION_URL: `${BASE_URL}/load`,
    REPORT_DATA: `${BASE_URL}/report-data/`,
    CHANNELS: `${BASE_URL}/channel`,
    GET_PAGELIST: `${BASE_URL}/channel/getpagelist`,
    GET_PHONELIST: `${BASE_URL}/channel/getphonelist`,
    VERIFY_CHANNEL: `${BASE_URL}/subscription/get/contract`,
    GET_PAGELISTSUB: `${BASE_URL}/subscription/getpagelist`,
    INSERT_CHANNEL: `${BASE_URL}/channel/insertchannel`,
    ACTIVATE_CHANNEL: `${BASE_URL}/channel/activatechannel`,
    EXEC_SUB: `${BASE_URL}/subscription/createsubscription`,
    VALIDATE_NEW_USER: `${BASE_URL}/subscription/validateusername`,
    CURRENCYLIST: `${BASE_URL}/subscription/currencylist`,
    COUNTRYLIST: `${BASE_URL}/subscription/countrylist`,
    ACTIVATION_USER: `${BASE_URL}/subscription/activateuser`,
    DELETE_CHANNEL: `${BASE_URL}/channel/deletechannel`,
    CHECK_PAYMENTPLAN: `${BASE_URL}/channel/checkpaymentplan`,
    REESCHEDULECALL: `${BASE_URL}/campaign/hsmcall`,
    SEND_INVOICE: `${BASE_URL}/billing/sendinvoice`,
    CONVERSATION: `${BASE_URL}/ticket`,

    PERSON: `${BASE_URL}/person`,

    CULQI: `${BASE_URL}/payment`,

    CHATFLOW: `${CHATFLOW_URL}`,

    BILLINGCREATEINVOICE: `${BASE_URL}/payment/createinvoice`,
    BILLINGCREATECREDITNOTE: `${BASE_URL}/payment/createcreditnote`,
    BILLINGREGULARIZEINVOICE: `${BASE_URL}/payment/regularizeinvoice`,
    GETEXCHANGERATE: `${BASE_URL}/payment/getexchangerate`,
    BILLINGEMITINVOICE: `${BASE_URL}/payment/emitinvoice`,
    BILLINGCHARGEINVOICE: `${BASE_URL}/payment/chargeinvoice`,
    BILLINGCREATEBALANCE: `${BASE_URL}/payment/createbalance`,

    RECOVERPASSWORD: `${BASE_URL}/subscription/recoverpassword`,
    CHANGEPASSWORD: `${BASE_URL}/subscription/changepassword`,

    VALIDATE_CHANNELS: `${BASE_URL}/subscription/validatechannels`,

    CARDCREATE: `${BASE_URL}/payment/cardcreate`,
    CARDDELETE: `${BASE_URL}/payment/carddelete`,
    CARDGET: `${BASE_URL}/payment/cardget`,

    VOXIMPLANT_GET_CATEGORIES: `${BASE_URL}/voximplant/getphonenumbercategories`,
    VOXIMPLANT_GET_COUNTRYSTATES: `${BASE_URL}/voximplant/getphonenumbercountrystates`,
    VOXIMPLANT_GET_REGIONS: `${BASE_URL}/voximplant/getphonenumberregions`,

    VOXIMPLANT_GET_MAXIMUMCONSUMPTION: `${BASE_URL}/voximplant/getmaximumconsumption`,
    VOXIMPLANT_TRANSFER_ACCOUNTBALANCE: `${BASE_URL}/voximplant/transferaccountbalance`,
    VOXIMPLANT_GET_ACCOUNTBALANCE: `${BASE_URL}/voximplant/getaccountbalance`,

    VOXIMPLANT_GET_CALLRECORD: `${BASE_URL}/voximplant/getcallrecord`,

    VOXIMPLANT_UPDATE_SCENARIO: `${BASE_URL}/voximplant/updatescenario`,

    GOOGLE_EXCHANGECODE: `${BASE_URL}/google/exchangecode`,
    GOOGLE_LISTBLOGGER: `${BASE_URL}/google/listblogger`,
    GOOGLE_LISTYOUTUBE: `${BASE_URL}/google/listyoutube`,
    SYNCHRONIZE_TEMPLATE: `${BASE_URL}/channel/synchronizetemplate`,
    ADD_TEMPLATE: `${BASE_URL}/channel/addtemplate`,
    DELETE_TEMPLATE: `${BASE_URL}/channel/deletetemplate`,
    GET_GROUP_LIST: `${BASE_URL}/channel/getgrouplist`,

    BILLING_REPORTPDF: `${BASE_URL}/drawpdf`,

    PRODUCT_IMPORT: `${BASE_URL}/product/import`,
    POSTHISTORY_SCHEDULE: `${BASE_URL}/posthistory/schedulepost`,
    EVENTBOOKING_GOOGLE_LOGIN: `${BASE_URL}/event-booking/googlelogin`,
    EVENTBOOKING_GOOGLE_DISCONNECT: `${BASE_URL}/event-booking/googledisconnect`,
    EVENTBOOKING_GOOGLE_VALIDATE: `${BASE_URL}/event-booking/googlevalidate`,

    PAYMENTORDER_PAY: `${BASE_URL}/payment/newpayment`,

    CATALOG_BUSINESSLIST: `${BASE_URL}/catalog/getbusinesslist`,
    CATALOG_MANAGECATALOG: `${BASE_URL}/catalog/managecatalog`,
    CATALOG_SYNCHROCATALOG: `${BASE_URL}/catalog/synchrocatalog`,
    CATALOG_SYNCHROPRODUCT: `${BASE_URL}/catalog/synchroproduct`,
    CATALOG_IMPORTPRODUCT: `${BASE_URL}/catalog/importproduct`,
    CATALOG_MANAGEPRODUCT: `${BASE_URL}/catalog/manageproduct`,
    CATALOG_DELETEPRODUCT: `${BASE_URL}/catalog/deleteproduct`,
    CATALOG_DOWNLOADPRODUCT: `${BASE_URL}/catalog/downloadproduct`,

    PAYMENTORDER_NIUBIZ_CREATESESSIONTOKEN: `${BASE_URL}/paymentniubiz/createsessiontoken`,
    PAYMENTORDER_NIUBIZ_AUTHORIZETRANSACTION: `${BASE_URL}/paymentniubiz/authorizetransaction`,

    PAYMENTORDER_OPENPAY_GETPAYMENTORDER: `${BASE_URL}/paymentopenpay/getpaymentorder`,
    PAYMENTORDER_OPENPAY_PROCESSTRANSACTION: `${BASE_URL}/paymentopenpay/processtransaction`,

    PAYMENTORDER_IZIPAY_GETPAYMENTORDER: `${BASE_URL}/paymentizipay/getpaymentorder`,
    PAYMENTORDER_IZIPAY_PROCESSTRANSACTION: `${BASE_URL}/paymentizipay/processtransaction`,

    PAYMENTORDER_EPAYCO_GETPAYMENTORDER: `${BASE_URL}/paymentepayco/getpaymentorder`,
    PAYMENTORDER_EPAYCO_PROCESSTRANSACTION: `${BASE_URL}/paymentepayco/processtransaction`,

    GPT_THREADS: `${BASE_URL}/gpt/threads`,
    GPT_THREADS_DELETE: `${BASE_URL}/gpt/threads/delete`,
    GPT_ASSISTANT_NEW: `${BASE_URL}/gpt/assistants/new`,
    GPT_MESSAGES: `${BASE_URL}/gpt/assistants/messages`,
    GPT_FILE_DELETE: `${BASE_URL}/gpt/files/delete`,

    GPT_FILES: `${BASE_URL}/gpt/files`,
    GPT_ASSISTANTS_FILES: `${BASE_URL}/gpt/assistants/files`,
    GPT_ASSISTANTS_FILES_LIST: `${BASE_URL}/gpt/assistants/files/list`,
    GPT_ASSISTANTS_UPDATE: `${BASE_URL}/gpt/assistants/update`,
    GPT_ASSISTANTS_DELETE: `${BASE_URL}/gpt/assistants/delete`,
    GPT_ASSISTANTS_DELETE_MASSIVE: `${BASE_URL}/gpt/assistants/massivedelete`,

    LLAMA_CREATE_COLLECTION: `${BASE_URL}/llama/create_collection`,
    LLAMA_CREATE_COLLECTION_DOCUMENT: `${BASE_URL}/llama/create_collection_document`,
    LLAMA_CREATE_COLLECTION_DOCUMENTS: `${BASE_URL}/llama/create_collection_documents`,
    LLAMA_DELETE_COLLECTION: `${BASE_URL}/llama/delete_collection`,
    LLAMA_MASSIVE_DELETE_COLLECTION: `${BASE_URL}/llama/massive_delete`,
    LLAMA_EDIT_COLLECTION: `${BASE_URL}/llama/edit_collection`,
    LLAMA_ADD_FILE: `${BASE_URL}/llama/add_file`,
    LLAMA_DELETE_FILE: `${BASE_URL}/llama/delete_file`,
    LLAMA_QUERY: `${BASE_URL}/llama/query`,
    LLAMA_DELETE_THREAD: `${BASE_URL}/llama/delete_thread`,
    LLAMA_ADD_FILES: `${BASE_URL}/llama/add_files`,

    LLAMA_UPLOAD_FILES: `${BASE_URL}/llama/upload`,
    LLAMA_MESSAGE: `${BASE_URL}/llama/message`,

    CORP_URL: `${BASE_URL}/corp`,
    DELIVERY_ROUTING: `${BASE_URL}/delivery/routing`,
    PROCESSZIPINTEGRATION: `${BASE_URL}/integrationmanager/file_upload`,
    SAML_LOGIN: `${BASE_URL}/auth/idps/saml20/sso/login`,

    LLAMA3_CREATE_COLLECTION: `${BASE_URL}/llama3/create_collection`,
    LLAMA3_CREATE_COLLECTION_DOCUMENT: `${BASE_URL}/llama3/create_collection_document`,
    LLAMA3_CREATE_COLLECTION_DOCUMENTS: `${BASE_URL}/llama3/create_collection_documents`,
    LLAMA3_DELETE_COLLECTION: `${BASE_URL}/llama3/delete_collection`,
    LLAMA3_MASSIVE_DELETE_COLLECTION: `${BASE_URL}/llama3/massive_delete`,
    LLAMA3_EDIT_COLLECTION: `${BASE_URL}/llama3/edit_collection`,
    LLAMA3_ADD_FILE: `${BASE_URL}/llama3/add_file`,
    LLAMA3_ADD_FILES: `${BASE_URL}/llama3/add_files`,
    LLAMA3_DELETE_FILE: `${BASE_URL}/llama3/delete_file`,
    LLAMA3_QUERY: `${BASE_URL}/llama3/llama3_query`,
    LLAMA3_DELETE_THREAD: `${BASE_URL}/llama3/delete_thread`,
};