const paths = {
    DASHBOARD: '/dashboard',
    REPORTS: '/reports',
    TICKETS: '/tickets',
    EMAIL_INBOX: '/email_inbox',
    MESSAGE_INBOX: '/message_inbox',
    SUPERVISOR: '/supervisor',
    ORGANIZATIONS: '/organizations',
    CHANNELS: '/channels',
    CHANNELS_ADD: {
        path: '/channels/:id/add',
        resolve: (channelId: string | number) => `/channels/${channelId}/add`,
    },
    CHANNELS_ADD_CHATWEB: {
        path: '/channels/:id/add/chatweb',
        resolve: (channelId: string | number) => `/channels/${channelId}/add/chatweb`,
    },
    BILLING_SETUPS: '/billing_setups',
    CONFIGURATION: '/configuration',
    EXTRAS: '/extras',
    PROPERTIES: '/extras/properties',
    QUICKREPLIES: '/extras/quickreplies',
    USERS: '/extras/users',
    GROUPCONFIG: '/extras/groupconfig',    
    WHITELIST: '/extras/whitelist',    
    INAPPROPRIATEWORDS: '/extras/inappropriatewords',
    INTELLIGENTMODELS: '/extras/intelligentmodels',
    SLA: '/extras/sla',
    DOMAINS: '/extras/domains',
    PERSON: '/extras/person',
    MESSAGETEMPLATE: '/extras/messagetemplate',
    TIPIFICATIONS: '/extras/tipifications',
    INTEGRATIONMANAGER: '/extras/integrationmanager',
};

export default paths;
