export type ICalendarSchedule = {
    start: string,
    end: string,
    dow: number,
    status: string,
    overlap?: number,
}

export type ICalendarFormFields = {
    id: number,
    eventcode: string,
    eventname: string,
    location: string,
    description: string,
    color: string,
    status: string,
    notificationtype: string,
    hsmtemplatename: string,
    daysintothefuture: number,
    communicationchannelid: number,
    hsmtemplateid: number,
    operation: string,
    intervals: ICalendarSchedule[],
    variables: any[],
    durationtype: string,
    duration: number,
    maximumCapacity: number,
    timebeforeeventunit: string,
    timebeforeeventduration: number,
    timeaftereventunit: string,
    timeaftereventduration: number,
    statusreminder: string,
    remindertype: string,
    email: string,
    hsm: string,
    remindermailtemplateid: any,
    reminderemailtemplatename: any,
    remindervariablesemail: any[],
    reminderhsmtemplateid: any,
    reminderhsmtemplatename: any,
    remindervariableshsm: any[],
    reminderperiod: string,
    reminderfrecuency: number,
    reminderhsmcommunicationchannelid: number,
}