const actionType = {
    GET_DASHBOARD: 'dashboard/GET_DASHBOARD',
    GET_DASHBOARD_FAILURE: 'dashboard/GET_DASHBOARD_FAILURE',
    GET_DASHBOARD_SUCCESS: 'dashboard/GET_DASHBOARD_SUCCESS',
    GET_DASHBOARD_RESET: 'dashboard/GET_DASHBOARD_RESET',

    GET_DASHBOARDTEMPLATE: 'dashboard/GET_DASHBOARDTEMPLATE',
    GET_DASHBOARDTEMPLATE_FAILURE: 'dashboard/GET_DASHBOARDTEMPLATE_FAILURE',
    GET_DASHBOARDTEMPLATE_SUCCESS: 'dashboard/GET_DASHBOARDTEMPLATE_SUCCESS',
    GET_DASHBOARDTEMPLATE_RESET: 'dashboard/GET_DASHBOARDTEMPLATE_RESET',

    SAVE_DASHBOARDTEMPLATE: 'dashboard/SAVE_DASHBOARDTEMPLATE',
    SAVE_DASHBOARDTEMPLATE_FAILURE: 'dashboard/SAVE_DASHBOARDTEMPLATE_FAILURE',
    SAVE_DASHBOARDTEMPLATE_SUCCESS: 'dashboard/SAVE_DASHBOARDTEMPLATE_SUCCESS',
    SAVE_DASHBOARDTEMPLATE_RESET: 'dashboard/SAVE_DASHBOARDTEMPLATE_RESET',
};

export default actionType;
