const actionType = {
    CHARGE: 'culqi/CHARGE',
    CHARGE_FAILURE: 'culqi/CHARGE_FAILURE',
    CHARGE_SUCCESS: 'culqi/CHARGE_SUCCESS',
    CHARGE_RESET: 'culqi/CHARGE_RESET',

    SUBSCRIBE: 'culqi/SUBSCRIBE',
    SUBSCRIBE_FAILURE: 'culqi/SUBSCRIBE_FAILURE',
    SUBSCRIBE_SUCCESS: 'culqi/SUBSCRIBE_SUCCESS',
    SUBSCRIBE_RESET: 'culqi/SUBSCRIBE_RESET',

    UNSUBSCRIBE: 'culqi/UNSUBSCRIBE',
    UNSUBSCRIBE_FAILURE: 'culqi/UNSUBSCRIBE_FAILURE',
    UNSUBSCRIBE_SUCCESS: 'culqi/UNSUBSCRIBE_SUCCESS',
    UNSUBSCRIBE_RESET: 'culqi/UNSUBSCRIBE_RESET',
};

export default actionType;