const actionType = {
    CHARGE: 'culqi/CHARGE',
    CHARGE_FAILURE: 'culqi/CHARGE_FAILURE',
    CHARGE_SUCCESS: 'culqi/CHARGE_SUCCESS',
    CHARGE_RESET: 'culqi/CHARGE_RESET',

    SUBSCRIBE: 'culqi/SUBSCRIBE',
    SUBSCRIBE_FAILURE: 'culqi/SUBSCRIBE_FAILURE',
    SUBSCRIBE_SUCCESS: 'culqi/SUBSCRIBE_SUCCESS',
    SUBSCRIBE_RESET: 'culqi/SUBSCRIBE_RESET',

    UNSUBSCRIBE: 'culqi/UNSUBSCRIBE',
    UNSUBSCRIBE_FAILURE: 'culqi/UNSUBSCRIBE_FAILURE',
    UNSUBSCRIBE_SUCCESS: 'culqi/UNSUBSCRIBE_SUCCESS',
    UNSUBSCRIBE_RESET: 'culqi/UNSUBSCRIBE_RESET',

    SEND_INVOICE: 'culqi/SEND_INVOICE',
    SEND_INVOICE_FAILURE: 'culqi/SEND_INVOICE_FAILURE',
    SEND_INVOICE_SUCCESS: 'culqi/SEND_INVOICE_SUCCESS',
    SEND_INVOICE_RESET: 'culqi/SEND_INVOICE_RESET',

    CREATE_INVOICE: 'culqi/CREATE_INVOICE',
    CREATE_INVOICE_FAILURE: 'culqi/CREATE_INVOICE_FAILURE',
    CREATE_INVOICE_SUCCESS: 'culqi/CREATE_INVOICE_SUCCESS',
    CREATE_INVOICE_RESET: 'culqi/CREATE_INVOICE_RESET',
};

export default actionType;