const actionType = {
    PAGELIST: 'signup/PAGELIST',
    PAGELIST_FAILURE: 'signup/PAGELIST_FAILURE',
    PAGELIST_SUCCESS: 'signup/PAGELIST_SUCCESS',
    PAGELIST_RESET: 'signup/PAGELIST_RESET',
    SIGNUP: 'signup/SIGNUP',
    SIGNUP_FAILURE: 'signup/SIGNUP_FAILURE',
    SIGNUP_SUCCESS: 'signup/SIGNUP_SUCCESS',
    SIGNUP_RESET: 'signup/SIGNUP_RESET',
    ISVALID: 'signup/ISVALID',
    ISVALID_FAILURE: 'signup/ISVALID_FAILURE',
    ISVALID_SUCCESS: 'signup/ISVALID_SUCCESS',
    ISVALID_RESET: 'signup/ISVALID_RESET',
};

export default actionType;
