const actionType = {
    GET_LEAD: 'lead/GET_LEAD',
    GET_LEAD_FAILURE: 'lead/GET_LEAD_FAILURE',
    GET_LEAD_SUCCESS: 'lead/GET_LEAD_SUCCESS',
    GET_LEAD_RESET: 'lead/GET_LEAD_RESET',

    SAVE_LEAD: 'lead/INS_LEAD',
    SAVE_LEAD_FAILURE: 'lead/INS_LEAD_FAILURE',
    SAVE_LEAD_SUCCESS: 'lead/INS_LEAD_SUCCESS',
    SAVE_LEAD_RESET: 'lead/INS_LEAD_RESET',

    GET_ADVISERS: 'lead/GET_ADVISERS',
    GET_ADVISERS_FAILURE: 'lead/GET_ADVISERS_FAILURE',
    GET_ADVISERS_SUCCESS: 'lead/GET_ADVISERS_SUCCESS',
    GET_ADVISERS_RESET: 'lead/GET_ADVISERS_RESET',

    GET_SLARULES: 'lead/GET_SLARULES',
    GET_SLARULES_FAILURE: 'lead/GET_SLARULES_FAILURE',
    GET_SLARULES_SUCCESS: 'lead/GET_SLARULES_SUCCESS',
    GET_SLARULES_RESET: 'lead/GET_SLARULES_RESET',

    GET_PHASES: 'lead/GET_PHASES',
    GET_PHASES_FAILURE: 'lead/GET_PHASES_FAILURE',
    GET_PHASES_SUCCESS: 'lead/GET_PHASES_SUCCESS',
    GET_PHASES_RESET: 'lead/GET_PHASES_RESET',

    GET_LEADNOTES: 'lead/GET_LEADNOTES',
    GET_LEADNOTES_FAILURE: 'lead/GET_LEADNOTES_FAILURE',
    GET_LEADNOTES_SUCCESS: 'lead/GET_LEADNOTES_SUCCESS',
    GET_LEADNOTES_RESET: 'lead/GET_LEADNOTES_RESET',

    GET_LEADACTIVITIES: 'lead/GET_LEADACTIVITIES',
    GET_LEADACTIVITIES_FAILURE: 'lead/GET_LEADACTIVITIES_FAILURE',
    GET_LEADACTIVITIES_SUCCESS: 'lead/GET_LEADACTIVITIES_SUCCESS',
    GET_LEADACTIVITIES_RESET: 'lead/GET_LEADACTIVITIES_RESET',

    SAVE_LEADNOIE: 'lead/SAVE_LEADNOIE',
    SAVE_LEADNOIE_FAILURE: 'lead/SAVE_LEADNOIE_FAILURE',
    SAVE_LEADNOIE_SUCCESS: 'lead/SAVE_LEADNOIE_SUCCESS',
    SAVE_LEADNOIE_RESET: 'lead/SAVE_LEADNOIE_RESET',

    SAVE_LEADACTIVITY: 'lead/SAVE_LEADACTIVITY',
    SAVE_LEADACTIVITY_FAILURE: 'lead/SAVE_LEADACTIVITY_FAILURE',
    SAVE_LEADACTIVITY_SUCCESS: 'lead/SAVE_LEADACTIVITY_SUCCESS',
    SAVE_LEADACTIVITY_RESET: 'lead/SAVE_LEADACTIVITY_RESET',

    DISPLAY_LEAD: 'lead/DISPLAY_LEAD',
    DISPLAY_LEAD_RESET: 'lead/DISPLAY_LEAD_RESET',

    ARCHIVE_LEAD: 'lead/ARCHIVE_LEAD',
    ARCHIVE_LEAD_FAILURE: 'lead/ARCHIVE_LEAD_FAILURE',
    ARCHIVE_LEAD_SUCCESS: 'lead/ARCHIVE_LEAD_SUCCESS',
    ARCHIVE_LEAD_RESET: 'lead/ARCHIVE_LEAD_RESET',

    MARK_DONE_ACTIVITY: 'lead/MARK_DONE_ACTIVITY',
    MARK_DONE_ACTIVITY_FAILURE: 'lead/MARK_DONE_ACTIVITY_FAILURE',
    MARK_DONE_ACTIVITY_SUCCESS: 'lead/MARK_DONE_ACTIVITY_SUCCESS',
    MARK_DONE_ACTIVITY_RESET: 'lead/MARK_DONE_ACTIVITY_RESET',

    GET_LEAD_HISTORY: 'lead/GET_LEAD_HISTORY',
    GET_LEAD_HISTORY_FAILURE: 'lead/GET_LEAD_HISTORY_FAILURE',
    GET_LEAD_HISTORY_SUCCESS: 'lead/GET_LEAD_HISTORY_SUCCESS',
    GET_LEAD_HISTORY_RESET: 'lead/GET_LEAD_HISTORY_RESET',

    UPDATE_LEAD_TAGS: 'lead/UPDATE_LEAD_TAGS',
    UPDATE_LEAD_TAGS_FAILURE: 'lead/UPDATE_LEAD_TAGS_FAILURE',
    UPDATE_LEAD_TAGS_SUCCESS: 'lead/UPDATE_LEAD_TAGS_SUCCESS',
    UPDATE_LEAD_TAGS_RESET: 'lead/UPDATE_LEAD_TAGS_RESET',

    GET_LEAD_PRODUCTS_DOMAIN: 'lead/GET_LEAD_PRODUCTS_DOMAIN',
    GET_LEAD_PRODUCTS_DOMAIN_FAILURE: 'lead/GET_LEAD_PRODUCTS_DOMAIN_FAILURE',
    GET_LEAD_PRODUCTS_DOMAIN_SUCCESS: 'lead/GET_LEAD_PRODUCTS_DOMAIN_SUCCESS',
    GET_LEAD_PRODUCTS_DOMAIN_RESET: 'lead/GET_LEAD_PRODUCTS_DOMAIN_RESET',

    GET_LEAD_TAGS_DOMAIN: 'lead/GET_LEAD_TAGS_DOMAIN',
    GET_LEAD_TAGS_DOMAIN_FAILURE: 'lead/GET_LEAD_TAGS_DOMAIN_FAILURE',
    GET_LEAD_TAGS_DOMAIN_SUCCESS: 'lead/GET_LEAD_TAGS_DOMAIN_SUCCESS',
    GET_LEAD_TAGS_DOMAIN_RESET: 'lead/GET_LEAD_TAGS_DOMAIN_RESET',

    GET_PERSON_TYPE: 'lead/GET_PERSON_TYPE',
    GET_PERSON_TYPE_FAILURE: 'lead/GET_PERSON_TYPE_FAILURE',
    GET_PERSON_TYPE_SUCCESS: 'lead/GET_PERSON_TYPE_SUCCESS',
    GET_PERSON_TYPE_RESET: 'lead/GET_PERSON_TYPE_RESET',
    
    GET_LEAD_TEMPLATES: 'lead/GET_LEAD_TEMPLATES',
    GET_LEAD_TEMPLATES_SUCCESS: 'lead/GET_LEAD_TEMPLATES_SUCCESS',
    GET_LEAD_TEMPLATES_FAILURE: 'lead/GET_LEAD_TEMPLATES_FAILURE',
    GET_LEAD_TEMPLATES_RESET: 'lead/GET_LEAD_TEMPLATES_RESET',

    GET_LEAD_CHANNELS: 'lead/GET_LEAD_CHANNELS',
    GET_LEAD_CHANNELS_SUCCESS: 'lead/GET_LEAD_CHANNELS_SUCCESS',
    GET_LEAD_CHANNELS_FAILURE: 'lead/GET_LEAD_CHANNELS_FAILURE',
    GET_LEAD_CHANNELS_RESET: 'lead/GET_LEAD_CHANNELS_RESET',

    GET_GROUPS: 'lead/GET_GROUPS',
    GET_GROUPS_SUCCESS: 'lead/GET_GROUPS_SUCCESS',
    GET_GROUPS_FAILURE: 'lead/GET_GROUPS_FAILURE',
    GET_GROUPS_RESET: 'lead/GET_GROUPS_RESET',

    GET_URGENCY: 'lead/GET_URGENCY',
    GET_URGENCY_SUCCESS: 'lead/GET_URGENCY_SUCCESS',
    GET_URGENCY_FAILURE: 'lead/GET_URGENCY_FAILURE',
    GET_URGENCY_RESET: 'lead/GET_URGENCY_RESET',

    GET_IMPACT: 'lead/GET_IMPACT',
    GET_IMPACT_SUCCESS: 'lead/GET_IMPACT_SUCCESS',
    GET_IMPACT_FAILURE: 'lead/GET_IMPACT_FAILURE',
    GET_IMPACT_RESET: 'lead/GET_IMPACT__RESET',

    GET_PRIORITY: 'lead/GET_PRIORITY',
    GET_PRIORITY_SUCCESS: 'lead/GET_PRIORITY_SUCCESS',
    GET_PRIORITY_FAILURE: 'lead/GET_PRIORITY_FAILURE',
    GET_PRIORITY_RESET: 'lead/GET_PRIORITY_RESET',

    GET_COMPANY: 'lead/GET_COMPANY',
    GET_COMPANY_SUCCESS: 'lead/GET_COMPANY_SUCCESS',
    GET_COMPANY_FAILURE: 'lead/GET_COMPANY_FAILURE',
    GET_COMPANY_RESET: 'lead/GET_COMPANY_RESET',
};

export default actionType;
