const actionType = {
    ITEMS: 'watsonx/ITEMS',
    ITEMS_FAILURE: 'watsonx/ITEMS_FAILURE',
    ITEMS_SUCCESS: 'watsonx/ITEMS_SUCCESS',
    ITEMS_RESET: 'watsonx/ITEMS_RESET',
    
    CREATEMENTION_MAIN: 'watsonx/CREATEMENTION_MAIN',
    CREATEMENTION_MAIN_SUCCESS: 'watsonx/CREATEMENTION_MAIN_SUCCESS',
    CREATEMENTION_MAIN_FAILURE: 'watsonx/CREATEMENTION_MAIN_FAILURE',
    CREATEMENTION_MAIN_RESET: 'watsonx/CREATEMENTION_MAIN_RESET',
    
    INTENT: 'watsonx/INTENT',
    INTENT_SUCCESS: 'watsonx/INTENT_SUCCESS',
    INTENT_FAILURE: 'watsonx/INTENT_FAILURE',
    INTENT_RESET: 'watsonx/INTENT_RESET',
    
    ITEMSDETAIL: 'watsonx/ITEMSDETAIL',
    ITEMSDETAIL_FAILURE: 'watsonx/ITEMSDETAIL_FAILURE',
    ITEMSDETAIL_SUCCESS: 'watsonx/ITEMSDETAIL_SUCCESS',
    ITEMSDETAIL_RESET: 'watsonx/ITEMSDETAIL_RESET',
    
    DELETEITEMS: 'watsonx/DELETEITEMS',
    DELETEITEMS_SUCCESS: 'watsonx/DELETEITEMS_SUCCESS',
    DELETEITEMS_FAILURE: 'watsonx/DELETEITEMS_FAILURE',
    DELETEITEMS_RESET: 'watsonx/DELETEITEMS_RESET',
    
    ENTITY: 'watsonx/ENTITY',
    ENTITY_SUCCESS: 'watsonx/ENTITY_SUCCESS',
    ENTITY_FAILURE: 'watsonx/ENTITY_FAILURE',
    ENTITY_RESET: 'watsonx/ENTITY_RESET',

    SETROW: 'watsonx/SETROW',
    
    MENTIONS: 'watsonx/MENTIONS',
    MENTIONS_SUCCESS: 'watsonx/MENTIONS_SUCCESS',
    MENTIONS_FAILURE: 'watsonx/MENTIONS_FAILURE',
    MENTIONS_RESET: 'watsonx/MENTIONS_RESET',
    
    BULKLOAD: 'watsonx/BULKLOAD',
    BULKLOAD_SUCCESS: 'watsonx/BULKLOAD_SUCCESS',
    BULKLOAD_FAILURE: 'watsonx/BULKLOAD_FAILURE',
    BULKLOAD_RESET: 'watsonx/BULKLOAD_RESET',
    
    CONFLICTS: 'watsonx/CONFLICTS',
    CONFLICTS_FAILURE: 'watsonx/CONFLICTS_FAILURE',
    CONFLICTS_SUCCESS: 'watsonx/CONFLICTS_SUCCESS',
    CONFLICTS_RESET: 'watsonx/CONFLICTS_RESET',
    
    RESOLVECONFLICT: 'watsonx/RESOLVECONFLICT',
    RESOLVECONFLICT_SUCCESS: 'watsonx/RESOLVECONFLICT_SUCCESS',
    RESOLVECONFLICT_FAILURE: 'watsonx/RESOLVECONFLICT_FAILURE',
    RESOLVECONFLICT_RESET: 'watsonx/RESOLVECONFLICT_RESET',

    EXPORTITEMS: 'watsonx/EXPORTITEMS',
    EXPORTITEMS_FAILURE: 'watsonx/EXPORTITEMS_FAILURE',
    EXPORTITEMS_SUCCESS: 'watsonx/EXPORTITEMS_SUCCESS',
    EXPORTITEMS_RESET: 'watsonx/EXPORTITEMS_RESET',
};

export default actionType;