const actionType = {
    GET_ORDER: 'orders/GET_ORDER',
    GET_ORDER_SUCCESS: 'orders/GET_ORDER_SUCCESS',
    GET_ORDER_FAILURE: 'orders/GET_ORDER_FAILURE',
    GET_ORDER_RESET: 'orders/GET_ORDER_RESET',
    GET_ORDERDETAIL: 'orders/GET_ORDERDETAIL',
    GET_ORDERDETAIL_SUCCESS: 'orders/GET_ORDERDETAIL_SUCCESS',
    GET_ORDERDETAIL_FAILURE: 'orders/GET_ORDERDETAIL_FAILURE',
    GET_ORDERDETAIL_RESET: 'orders/GET_ORDERDETAIL_RESET',
};

export default actionType;