const actionType = {
    GET_AGENTS: 'ticket/GET_AGENTS',
    GET_AGENTS_FAILURE: 'ticket/GET_AGENTS_FAILURE',
    GET_AGENTS_SUCCESS: 'ticket/GET_AGENTS_SUCCESS',
    GET_AGENTS_RESET: 'ticket/GET_AGENTS_RESET',

    GET_TICKETS: 'ticket/GET_TICKETS',
    GET_TICKETS_FAILURE: 'ticket/GET_TICKETS_FAILURE',
    GET_TICKETS_SUCCESS: 'ticket/GET_TICKETS_SUCCESS',
    GET_TICKETS_RESET: 'ticket/GET_TICKETS_RESET',

    GET_INTERACTIONS: 'ticket/GET_INTERACTIONS',
    GET_INTERACTIONS_FAILURE: 'ticket/GET_INTERACTIONS_FAILURE',
    GET_INTERACTIONS_SUCCESS: 'ticket/GET_INTERACTIONS_SUCCESS',
    GET_INTERACTIONS_RESET: 'ticket/GET_INTERACTIONS_RESET',

    GET_PERSON: 'ticket/GET_PERSON',
    GET_PERSON_FAILURE: 'ticket/GET_PERSON_FAILURE',
    GET_PERSON_SUCCESS: 'ticket/GET_PERSON_SUCCESS',
    GET_PERSON_RESET: 'ticket/GET_PERSON_RESET',

    GET_TICKETS_BY_PERSON: 'ticket/GET_TICKETS_BY_PERSON',
    GET_TICKETS_BY_PERSON_FAILURE: 'ticket/GET_TICKETS_BY_PERSON_FAILURE',
    GET_TICKETS_BY_PERSON_SUCCESS: 'ticket/GET_TICKETS_BY_PERSON_SUCCESS',
    GET_TICKETS_BY_PERSON_RESET: 'ticket/GET_TICKETS_BY_PERSON_RESET',

    GET_TIPIFICATION_LEVEL_2: 'ticket/GET_TIPIFICATION_LEVEL_2',
    GET_TIPIFICATION_LEVEL_2_FAILURE: 'ticket/GET_TIPIFICATION_LEVEL_2_FAILURE',
    GET_TIPIFICATION_LEVEL_2_SUCCESS: 'ticket/GET_TIPIFICATION_LEVEL_2_SUCCESS',
    GET_TIPIFICATION_LEVEL_2_RESET: 'ticket/GET_TIPIFICATION_LEVEL_2_RESET',

    GET_TIPIFICATION_LEVEL_3: 'ticket/GET_TIPIFICATION_LEVEL_3',
    GET_TIPIFICATION_LEVEL_3_FAILURE: 'ticket/GET_TIPIFICATION_LEVEL_3_FAILURE',
    GET_TIPIFICATION_LEVEL_3_SUCCESS: 'ticket/GET_TIPIFICATION_LEVEL_3_SUCCESS',
    GET_TIPIFICATION_LEVEL_3_RESET: 'ticket/GET_TIPIFICATION_LEVEL_3_RESET',

    CLOSE_TICKET: 'ticket/CLOSE_TICKET',
    CLOSE_TICKET_FAILURE: 'ticket/CLOSE_TICKET_FAILURE',
    CLOSE_TICKET_SUCCESS: 'ticket/CLOSE_TICKET_SUCCESS',
    CLOSE_TICKET_RESET: 'ticket/CLOSE_TICKET_RESET',
    
    REPLY_TICKET: 'ticket/REPLY_TICKET',
    REPLY_TICKET_FAILURE: 'ticket/REPLY_TICKET_FAILURE',
    REPLY_TICKET_SUCCESS: 'ticket/REPLY_TICKET_SUCCESS',
    REPLY_TICKET_RESET: 'ticket/REPLY_TICKET_RESET',

    REASSIGN_TICKET: 'ticket/REASSIGN_TICKET',
    REASSIGN_TICKET_FAILURE: 'ticket/REASSIGN_TICKET_FAILURE',
    REASSIGN_TICKET_SUCCESS: 'ticket/REASSIGN_TICKET_SUCCESS',
    REASSIGN_TICKET_RESET: 'ticket/REASSIGN_TICKET_RESET',
    
    GET_DATA_TICKET: 'ticket/GET_DATA_TICKET',
    GET_DATA_TICKET_FAILURE: 'ticket/GET_DATA_TICKET_FAILURE',
    GET_DATA_TICKET_SUCCESS: 'ticket/GET_DATA_TICKET_SUCCESS',
    GET_DATA_TICKET_RESET: 'ticket/GET_DATA_TICKET_RESET',


    SELECT_TICKET: 'ticket/SELECT_TICKET',
    RESET_SELECT_TICKET: 'ticket/RESET_SELECT_TICKET',

    SHOW_INFO_PANEL: 'ticket/SHOW_INFO_PANEL',
    SET_USER_TYPE: 'ticket/SET_USER_TYPE',

    SELECT_AGENT: 'ticket/SELECT_AGENT',
    REPLY_MESSAGE: 'ticket/REPLY_MESSAGE',
    ADD_TICKET: 'ticket/ADD_TICKET',
    MODIFY_TICKET: 'ticket/MODIFY_TICKET',
    RESET_SELECT_AGENT: 'ticket/RESET_SELECT_AGENT',
    NEW_MESSAGE_FROM_CLIENT: 'ticket/NEW_MESSAGE_FROM_CLIENT',
};

export default actionType;
