name: Deploy on DEVELOP

on:
  push:
    branches:
      - dev-feature

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.21.3' # Uddsar la versión de Node.js requerida

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Install IBM Cloud CLI
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud config --check-version=false

    - name: Log in to IBM Cloud
      run: |
        ibmcloud login --apikey ${{ secrets.IBM_API_KEY }} -r us-south
        ibmcloud resource target --resource-group default

    - name: Sync build folder to IBM Cloud Object Storage
      run: |
        ibmcloud cos config auth --apikey ${{ secrets.IBM_API_KEY }}
        ibmcloud cos config crn --crn ${{ secrets.IBM_SERVICE_ID_CRN }}
        ibmcloud cos config region --region us-south
        ibmcloud cos upload --bucket scanvirus-cos-static-web-hosting-w26 --key build/ --file build/ --recursive
