name: Deploy to IBM Cloud Object Storage

on:
  push:
    branches:
      - dev-feature

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.21.3' # Usa la versión de Node.js requerida

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Set up AWS CLI
      run: |
        sudo apt-get install awscli

    - name: Configure AWS CLI
      run: |
        echo "[default]" > ~/.aws/config
        echo "region = us-south" >> ~/.aws/config
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
        echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

    - name: Sync build folder to IBM Cloud Object Storage
      run: |
        aws --endpoint-url https://s3.us-south.cloud-object-storage.appdomain.cloud s3 cp ./build/ s3://scanvirus-cos-static-web-hosting-w26/ --recursive