name: CI

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy_cos:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm

      - name: Install deps
        run: npm install
        
      - name: Run build
        run: npm run build_no_ci

      - name: List files and folders
        run: ls -l
        
      - name: Get IAM access token
        run: |
          export ACCESS_TOKEN=$( curl -X "POST" "https://iam.cloud.ibm.com/oidc/token" \
               -H 'Accept: application/json' \
               -H 'Content-Type: application/x-www-form-urlencoded' \
               --data-urlencode "apikey=${{ secrets.LARAIGO_DEV_APIKEY }}" \
               --data-urlencode "response_type=cloud_iam" \
               --data-urlencode "grant_type=urn:ibm:params:oauth:grant-type:apikey" | jq --raw-output '.access_token' )
               
      - name: Set current directory path
        run: |
          BASE_DIRECTORY=./build
          FONT_DIRECTORY=./build/fonts
          STATIC_CSS_DIRECTORY=./build/static/css
          STATIC_JS_DIRECTORY=./build/static/js
          STATIC_MEDIA_DIRECTORY=./build/static/media
        
      - name: Go to build fonder
        run: cd ./build
        
      # The next file iteration gives the relative path
      - name: Once got the token, files must be uploaded one by one (token usually expires in 3600 seconds?)
        run: |
          for build_file in ./*; do
            curl -X "PUT" "https://s3.us-south.cloud-object-storage.appdomain.cloud/laraigo-dev/$build_file" \
                 -H "Authorization: bearer $ACCESS_TOKEN" \
                 -H "Content-Type: $(file -b --mime-type $build_file)" \
                 -d "@$build_file"
          done;

      - name: Upload fonts
        run: |
          for build_file in ./fonts/*; do
            curl -X "PUT" "https://s3.us-south.cloud-object-storage.appdomain.cloud/laraigo-dev/$build_file" \
                 -H "Authorization: bearer $ACCESS_TOKEN" \
                 -H "Content-Type: $(file -b --mime-type $build_file)" \
                 -d "@$build_file"
          done;

      - name: Upload css
        run: |
          for build_file in ./static/css/*; do
            curl -X "PUT" "https://s3.us-south.cloud-object-storage.appdomain.cloud/laraigo-dev/$build_file" \
                 -H "Authorization: bearer $ACCESS_TOKEN" \
                 -H "Content-Type: $(file -b --mime-type $build_file)" \
                 -d "@$build_file"
          done;

      - name: Upload js
        run: |
          for build_file in ./static/js/*; do
            curl -X "PUT" "https://s3.us-south.cloud-object-storage.appdomain.cloud/laraigo-dev/$build_file" \
                 -H "Authorization: bearer $ACCESS_TOKEN" \
                 -H "Content-Type: $(file -b --mime-type $build_file)" \
                 -d "@$build_file"
          done;

      - name: Upload media
        run: |
          for build_file in ./static/media/*; do
            curl -X "PUT" "https://s3.us-south.cloud-object-storage.appdomain.cloud/laraigo-dev/$build_file" \
                 -H "Authorization: bearer $ACCESS_TOKEN" \
                 -H "Content-Type: $(file -b --mime-type $build_file)" \
                 -d "@$build_file"
          done;
          
      - name: End of workflow
        run: echo "Upload finished"

