export * as CommonService from './service/common';
export * as ChannelsService from './service/channels';
export * as InboxService from './service/inbox';
export * as PersonService from './service/person';
export * as ActivationUserService from './service/activationuser';
export * as CulqiService from './service/culqi';
export * as SubscriptionService from './service/subscription';
export * as DashboardService from './service/dashboard';
export * as VoximplantService from './service/voximplant';
export * as GoogleService from './service/google';
// export * as WitaiService from './service/witai';
export * as ProductService from './service/product';
export * as CalendarService from './service/calendar';